6575 PRINT "             @#######@             "
6576 PRINT "            .#########.            "
6577 PRINT " "
6578 PRINT " "
6579 PRINT "              a@#@#@a              "
6580 PRINT "             l#######/a.           "
6581 PRINT "             a#########@           "
6582 PRINT "             l##########i          "
6583 PRINT "            .@#######@#@.          "
6584 PRINT "            ia#######a##.          "
6585 PRINT "             ./#####/l##i          "
6586 PRINT "              ./@#@/..@#l          "
6587 PRINT "  .ai          l@#@i  a@.      .   "
6588 PRINT " ./ia/l       a#####a .i    .l//l  "
6589 PRINT "a@@l.#aaaiilla#######aii. iaa@..@/."
6590 PRINT "/ @@.#a.#ia@l#########a@al#.a#i/@l@"
6591 PRINT "#.l@ aai#la#i#########l#al#ia@ @/./"
6592 PRINT "#l / .a @li#i########@i#il@.li @.l#"
6593 PRINT "/l .    ll @l#########l/ la .  l l@"
6594 PRINT ".i       . a@@a#####/#@l ..      ll"
6595 PRINT "          a#@ia#####al##a.       . "
6596 PRINT "      ial@#a. /#####/ .a@@@a.      "
6597 PRINT "    iia##/.  .#######.  .l@@l.     "
6598 PRINT "    iaal.    a#######a     laai    "
6599 PRINT "             @#######@             "
6600 PRINT "            .#########.            "
6601 PRINT " "
6602 PRINT "                . .                "
6603 PRINT "             ./#####a              "
6604 PRINT "             a#######//i           "
6605 PRINT "             /##########.          "
6606 PRINT "             a##########l          "
6607 PRINT "            i########@##.          "
6608 PRINT "            i/#######a##.          "
6609 PRINT "             i/#####/l##i          "
6610 PRINT "              i/@#@/..##l          "
6611 PRINT "  .l          .i@#@i  /@.      .   "
6612 PRINT " ./l/ai       a#####a .l    .l/aa  "
6613 PRINT "l@@.i@lai..lia#######aii. iaa@i @@i"
6614 PRINT "al#aa#ii@la/a#########a//l@ii#al#a@"
6615 PRINT "a.#li#.a#./#l#########i#a.#a.#ll#il"
6616 PRINT "@ ai a i#.l#i#########i#l.#l /..@ @"
6617 PRINT "/ .. .  /  @l#########i@  @. i  a a"
6618 PRINT "a       .  a@#@#####@#/a  l       i"
6619 PRINT "          a##ia#####al##a          "
6620 PRINT "      ili/#a. /#####/ .a#@/a.      "
6621 PRINT "    ..a##/i  .#######.  .a@@l      "
6622 PRINT "   .l/@a.    a#######a    .l//i    "
6623 PRINT "             @#######@             "
6624 PRINT "            .#########.            "
6625 PRINT " "
6626 PRINT "               illli               "
6627 PRINT "             .@#####/.             "
6628 PRINT "             a#######/@i           "
6629 PRINT "             /##########.          "
6630 PRINT "             /##########i          "
6631 PRINT "            /########/#@.          "
6632 PRINT "            ./#######a##.          "
6633 PRINT "             i@#####@l##i          "
6634 PRINT "              ia@#@a. @#i          "
6635 PRINT "  .i           i@#@i  a@.      .   "
6636 PRINT " ./a/l.       /#####a  .    .l/a/. "
6637 PRINT "l@/ a/aa. .iia#######l.i. .la@l /@i"
6638 PRINT "//#.@@ a@l///#########///l@l @@.#//"
6639 PRINT "ia#./a @@ @@l#########i@@ @@ /@.#/i"
6640 PRINT "ai/ ai // //i#########.@/ /@ ia aal"
6641 PRINT "i.i .  al lal#########ial la  i il."
6642 PRINT "       .. .l@@@#####@#/a. .l       "
6643 PRINT "          l##l/#####aa##l          "
6644 PRINT "      iii/#/. /#####/ i/#/aa.      "
6645 PRINT "     .a##@i  .#######.  i/#@i      "
6646 PRINT "   .a@@ai    a#######a    .a@/l    "
6647 PRINT "             @#######@             "
6648 PRINT "            .#########.            "
6649 PRINT " "
6650 PRINT "              .laaal               "
6651 PRINT "             i######@.             "
6652 PRINT "             /#######/@@           "
6653 PRINT "             /##########.          "
6654 PRINT "            .@#########@           "
6655 PRINT "            @########/##           "
6656 PRINT "            ./#######a##.          "
6657 PRINT "             i@#####@i##l          "
6658 PRINT "              ia/@/a. /#i          "
6659 PRINT "  ..           i@#/.  l/       ..  "
6660 PRINT " i///i        /#####a  .     l/a/i "
6661 PRINT "l#l //al.  i.a#######l.i  .la// l#a"
6662 PRINT "/@@i#/ //l@/@#########//@l/a /#.@@a"
6663 PRINT ".@@.#l.#a.#al#########ia#./#.a#.@@."
6664 PRINT "i/l @..#l.#ai#########.a#.a#../ l/i"
6665 PRINT ".l. i  @. @ia#########ii@ .@  i .l "
6666 PRINT "       l  l.@@########/.a  l       "
6667 PRINT "          l##l/#####/a#@l          "
6668 PRINT "      .../#@i /#####/ l@#/ll.      "
6669 PRINT "      /##@l  .@#####@.  l@##l      "
6670 PRINT "   i/@#/l.   a#######a    i/#/l.   "
6671 PRINT "     i.      @#######@      ..     "
6672 PRINT "            .#########.            "
6673 PRINT " "
6674 PRINT "              ia///a.              "
6675 PRINT "             l#######. .           "
6676 PRINT "             /#######@@#.          "
6677 PRINT "             @##########i          "
6678 PRINT "            i@##########.          "
6679 PRINT "           .@########/@#.          "
6680 PRINT "            ./#######a##i          "
6681 PRINT "             l######@i##l          "
6682 PRINT "              ia/@/a. /#i          "
6683 PRINT "  .            i@#/.  l@       .i  "
6684 PRINT " l//a.        /#####a  .     i///l "
6685 PRINT "a#i @/ai   ../#######a.i  .la// i#/"
6686 PRINT "/#/i#a @/l@/@#########//@l// /#i@@l"
6687 PRINT ".#/i#li#ai#la#########la#.a#.a#.@@ "
6688 PRINT "./l @.i#li#ll#########il#ia#.i/ aai"
6689 PRINT " a. l .#..#.a#########i.#.i@  i ii."
6690 PRINT " .     a  a.@#########/ a  l       "
6691 PRINT "          l@#a/#####//#@i          "
6692 PRINT "         a#@l @#####/ l@#aii.      "
6693 PRINT "     ./@@#a. .@#####@.  l@##l      "
6694 PRINT "   la/#@a.   l#######l    l@#al.   "
6695 PRINT "    ili      @#######@      ii.    "
6696 PRINT "            .#########.            "
6697 PRINT " "
6698 PRINT "              l////ai              "
6699 PRINT "             l#######i .           "
6700 PRINT "             @#######@##.          "
6701 PRINT "             @##########i          "
6702 PRINT "            i###########i          "
6703 PRINT "           .#########/@#i          "
6704 PRINT "            ./#######a@#l          "
6705 PRINT "             l######@i@#a          "
6706 PRINT "              la@@/a. /#l          "
6707 PRINT "  .            i@#/.  i#.      .i  "
6708 PRINT " l//l.        /#####a  .     ia//a "
6709 PRINT "a#..@/a.   . /#######a..   ia/@ .@/"
6710 PRINT "a#ai#a.@al@/@#########@/@l// /#i@@l"
6711 PRINT ".#/.#ai#l.#la#########la#.a#.a@ @@ "
6712 PRINT "./a @ii#ai#ll#########ia#ia#.la /li"
6713 PRINT ".ll l. @i.#.a#########li@ l/ .. l ."
6714 PRINT "  .    a. /.@#@#######a a .i       "
6715 PRINT "       .  l@#a/#####//#@i          "
6716 PRINT "         a#@l @#####@.a##aii.      "
6717 PRINT "     .@@@#a.  @#####@  .a###a      "
6718 PRINT "  .la/#@a.   l#######l   .l@#ali   "
6719 PRINT "   .lai      @#######@      ili    "
6720 PRINT "            .#########.            "
6721 PRINT " "
6722 PRINT "              .lllal.              "
6723 PRINT "             l#######i             "
6724 PRINT "             @#######@@a           "
6725 PRINT "             ###########a          "
6726 PRINT "             @##########/          "
6727 PRINT "           ./########@@#a          "
6728 PRINT "            l@#######a@#a          "
6729 PRINT "             a#######a@#/          "
6730 PRINT "  ll          a@@@#@l /#@     i/a. "
6731 PRINT "i///@l        ..@#/i  l#/   ./@la@a"
6732 PRINT "@#l @//i      a@###@i ./i .l//@ a#/"
6733 PRINT "i#/i#/.@/a/@l/#######aa@/a@@./#i@#."
6734 PRINT ".#a.#ai#l.#l@#########aa@.a#ia# /@ "
6735 PRINT " /l @il#ll#a/#########l/#ia#ii/ la "
6736 PRINT " l. l .#i.#i/#########ll# i@ .i .i "
6737 PRINT "       /  @.@#########a./ .a       "
6738 PRINT "       .  l.##########/ i  .       "
6739 PRINT "     li   i/#a@#####@@#l.   ll     "
6740 PRINT "  /lla#/l@##@.@#####@l###@/@#alaa  "
6741 PRINT "  i#######/l. ####### ia/#######.  "
6742 PRINT "   .laaal.   i#######i   .illaa.   "
6743 PRINT "             /#######/             "
6744 PRINT "            .#########.            "
6745 PRINT "################@@#################"
6746 PRINT "###############i  .ia@#############"
6747 PRINT "##############l       /############"
6748 PRINT "##############        i#@##########"
6749 PRINT "############/l         . a#########"
6750 PRINT "############.            l#########"
6751 PRINT "############@i           a#########"
6752 PRINT "#############l        l  #####@####"
6753 PRINT "###/a@#######@. ..   ia .###/iii/##"
6754 PRINT "#/ila.l@######@l....i/a  @/li.@a .l"
6755 PRINT ".. /a /lia/aa##/  i/#@.  i.@a i/ ii"
6756 PRINT "l. @. @l.@a.il.     lil i@ i#.i#l /"
6757 PRINT "/./#.a@ .#i l        .i l@..#@.##aa"
6758 PRINT "//##i## l#i           . a#a.##/####"
6759 PRINT "####@##.@#li.         iia##i#######"
6760 PRINT "#######/##l/          l//##@#######"
6761 PRINT "##########@a          .############"
6762 PRINT "###########i           /###########"
6763 PRINT "##########@. a       i i@##########"
6764 PRINT "#@@#@l###a  i@       /  .a##@i##/##"
6765 PRINT "#/.li ia.  i@/       //.  .a. .i./#"
6766 PRINT "##i      i/##a       a##a.      i##"
6767 PRINT "###@@/al/####.       .####/lla/a###"
6768 PRINT "############/         /############"
6769 PRINT "###############/. i/###############"
6770 PRINT "##############/     .l#############"
6771 PRINT "##############.       l############"
6772 PRINT "#############@        ./l/#########"
6773 PRINT "############a.           i#########"
6774 PRINT "############i            i#########"
6775 PRINT "#############i        .  a#########"
6776 PRINT "#############i        /  /####@@###"
6777 PRINT "###ll@#######@. ..   ./  /##/i.ia@#"
6778 PRINT "@a./a.l@######@a. ..i@/  /@ll./@ .l"
6779 PRINT ".. @l.@liaala##a  ./@@.  l.// i@ .a"
6780 PRINT "/. @. @ii@/.il.     iil l# .#.i#l @"
6781 PRINT "# a#il@ .#i i         . a#..#ai##i/"
6782 PRINT "@i##l/#.l#l             /#l.##l##@/"
6783 PRINT "#@##/##i/#/           . @#@i#######"
6784 PRINT "#######/##@i          il###@#######"
6785 PRINT "###########l           /###########"
6786 PRINT "###########. i         l###########"
6787 PRINT "##########/  a       l .@##########"
6788 PRINT "#@##a/##@l  l/       /.  l@##l/##/#"
6789 PRINT "#.lli aa.  i@/       //.  .al iii.#"
6790 PRINT "#a       i/##l       a##a.       a#"
6791 PRINT "##/a/lii/###@.       .@###/i.ilia##"
6792 PRINT "############/         /############"
6793 PRINT "##############l       a############"
6794 PRINT "#############@.       .@###########"
6795 PRINT "#############/         aal@########"
6796 PRINT "############l.            a########"
6797 PRINT "###########/              a########"
6798 PRINT "############/.            @########"
6799 PRINT "############@.        ii .#########"
6800 PRINT "##@/#########a  .     ai i####/la##"
6801 PRINT "#aii.a########l. .   i#. .##/i./a.a"
6802 PRINT ". /#.ila@######@. iaa#@. .aial.@a i"
6803 PRINT "/ ./ .@.ili.i@a.   i/@.. il.#. /i a"
6804 PRINT "@ i@ i/ l#i.i.       .l .@i /i.#l @"
6805 PRINT "#ll#ll/ l#.             i#i @ll#/.#"
6806 PRINT "#//#@a#.a#l             /#ai#/@##a#"
6807 PRINT "#######a/#@            .##/a#######"
6808 PRINT "#######@###i           l###########"
6809 PRINT "###########.           l###########"
6810 PRINT "##########/  i         .###########"
6811 PRINT "##########l il       i  /##########"
6812 PRINT "@##a/###@i  al       ai  l@###l/##/"
6813 PRINT "i//l a@l   i#l       l@.   l@a laa."
6814 PRINT ".        ./##l       l##a.        ."
6815 PRINT "/i.i   i/###@         @###a.     .a"
6816 PRINT "#####/a#####a         a#####ala@//#"
6817 PRINT "#############l          @/a########"
6818 PRINT "############@i          i  a#######"
6819 PRINT "###########i               l#######"
6820 PRINT "###########a               a#######"
6821 PRINT "############a          .  .########"
6822 PRINT "############a          /  i########"
6823 PRINT "#@@#########@i  .     .@  l#####aa#"
6824 PRINT "ai.i/########@i ..   .a/  .##@l.ili"
6825 PRINT " @#.ii/########a. .li/#@  .@aii.#@."
6826 PRINT " ./ .@.illii@#/l   a/#/.  ..i@  /. "
6827 PRINT ". /. / i#@.i.i       l.l  /. / .@  "
6828 PRINT "/ /a /  @l i.         .. l@  / a# a"
6829 PRINT "#a/#i@i @a               @@ l@i#@l#"
6830 PRINT "####@#/.##.             i##.@######"
6831 PRINT "#######l##l             /##a#######"
6832 PRINT "##########/             ###########"
6833 PRINT "##########l             /##########"
6834 PRINT "##########. i.          l##########"
6835 PRINT "#########@  a.       .. i##########"
6836 PRINT "#@/#####a. .@.       .a  i/####@l##"
6837 PRINT "#@.a##/.   a#        .#.   i/##ii@@"
6838 PRINT "..  li   ./##         #@l    ii    "
6839 PRINT "       .a###/         /##@l.       "
6840 PRINT " .    i#####l         i####@.      "
6841 PRINT "##########i                  @#####"
6842 PRINT "##########a                 .######"
6843 PRINT "###########a.               a######"
6844 PRINT "###########@i           a   @######"
6845 PRINT "###########@l          i@   @######"
6846 PRINT "a@##########@.  i.     l/   @####/i"
6847 PRINT "i i/#########/i       i@/   /##a..l"
6848 PRINT "#a.ii/#########a  .ila##/   /ail.i#"
6849 PRINT "/. l/ .iliia#@/i   l/##l.   . @l  /"
6850 PRINT "li i/ l@@.i.l.       ia.i  al al .a"
6851 PRINT "l/ il  #a .l           l. i@  ll /a"
6852 PRINT "i#ila .#l                 a#. /li#l"
6853 PRINT "l#/l#.i#/                 @#ii#a@#/"
6854 PRINT "###@#ai##.               l##/@#####"
6855 PRINT "#####@a##l            .l@##########"
6856 PRINT "#########/            a@@##########"
6857 PRINT "#########a            ...@#########"
6858 PRINT "#########i  .            a#########"
6859 PRINT "########@  .l         .  l#########"
6860 PRINT "#######/i  al         a.  l@######@"
6861 PRINT "i####@i   .#l         aa    l@###@."
6862 PRINT " i@@l    ./#l         l#l    .l@@. "
6863 PRINT "  .    .a###l         l##@i     .  "
6864 PRINT "      .@####.         .####/       "
6865 PRINT "###########a             .i  l#####"
6866 PRINT "##########@i             ai  l#####"
6867 PRINT "###########a   .        i#.  i#####"
6868 PRINT "###########@l   ii.     i@   .#####"
6869 PRINT "@###########@i         .@@    @###/"
6870 PRINT " i@##########@ai   ...i@@#    @#/. "
6871 PRINT ".ail/####@####@i   l@a##@@.  .aii/."
6872 PRINT " l#...ii. i#@l.     ia#@.    i..#a "
6873 PRINT " i/ .##/ l.i          ii.l  .@. aa "
6874 PRINT " ai  a#. il             l.  /a  i/ "
6875 PRINT " /l  /@                     @/  a@ "
6876 PRINT " #/  @#.          .........i#@..@#i"
6877 PRINT "l##la##/a//////@@@@@@@@@@@@@##@@##@"
6878 PRINT "###################################"
6879 PRINT "########///aaaaaaaaalllllaa########"
6880 PRINT "########i                 /########"
6881 PRINT "########.                 a########"
6882 PRINT "#######@   .              i########"
6883 PRINT "#######a  .l           .   ########"
6884 PRINT "######@i  la           a   a#######"
6885 PRINT "####@l    @a           /l   .a#####"
6886 PRINT "##@l     l#a           a@.    .a###"
6887 PRINT "@l      a##l           l#/.     .a@"
6888 PRINT ".      /###l           a###i      ."
6889 PRINT "##########/i    il.      i#@    l##"
6890 PRINT "###########a      .      l//    l##"
6891 PRINT "############ai.         i/#/    i##"
6892 PRINT "#############@l.   i.i.l###@    l#@"
6893 PRINT "i/############@    ia@a#####.   al."
6894 PRINT "a .illli.a##ai      .l@##l .      a"
6895 PRINT "a iaaai ..a.           a/ i    al i"
6896 PRINT "  .##a  /.               i/   l@.  "
6897 PRINT "   /#.  i                 .   @@   "
6898 PRINT "   @#.                       .##.  "
6899 PRINT "  i##i                       i##l  "
6900 PRINT "i a##l           ............a##/.."
6901 PRINT "ai@##@aaa//////@@@@@@@@@@@@@@####@@"
6902 PRINT "###################################"
6903 PRINT "######@////aaaaaaaalllllllla/######"
6904 PRINT "######l                    .@######"
6905 PRINT "######i                     a######"
6906 PRINT "#####@                      i######"
6907 PRINT "#####a   ..                 .######"
6908 PRINT "#####l   ai             i.   @#####"
6909 PRINT "###/i   .@i             ll   .a@###"
6910 PRINT "#/i     l#i             l@      l@#"
6911 PRINT "i      i##i             i#a       l"
6912 PRINT "       @##.             i##i       "
6913 PRINT "############@/.     ..i.l@####l    "
6914 PRINT "#############@l     ilal@#####/    "
6915 PRINT "######@@###@al.     .l/@###//@/    "
6916 PRINT ".iii.  .@@l            i@#/        "
6917 PRINT "aaaa. . i.               a. i .. .l"
6918 PRINT "/##l  /i                   la  ..a/"
6919 PRINT "l#@   ..                        l#l"
6920 PRINT "i#a                             a#a"
6921 PRINT "a#/                             @#@"
6922 PRINT "@##.                           .###"
6923 PRINT "###i                           i###"
6924 PRINT "###a             ..............a###"
6925 PRINT "###@laaaa//////@@@@@@@@@@@@@@@@####"
6926 PRINT "###################################"
6927 PRINT "####@@/////aaaaaaaalllllllllll/####"
6928 PRINT "###@.                         l####"
6929 PRINT "###l                           @###"
6930 PRINT "###.                           /###"
6931 PRINT "##@     .                      l###"
6932 PRINT "##a    ii                      i###"
6933 PRINT "#@i    al                 l    .@##"
6934 PRINT "l     .#l                 al     i/"
6935 PRINT "      a#l                 a@       "
6936 PRINT "     .##l                 a#l      "
6937 PRINT "i.    @/                  /#a      "
6938 PRINT ".     i.                  ./.    il"
6939 PRINT "@l .a                         /. i/"
6940 PRINT "l   l                             i"
6941 PRINT "."
6942 PRINT " "
6943 PRINT "."
6944 PRINT "i                                 l"
6945 PRINT "a                                 /"
6946 PRINT "/                                 @"
6947 PRINT "a                                i@"
6948 PRINT "#a              ................./#"
6949 PRINT "#/lllaaaa/////@@@@@@@@@@@@@@@@@@@##"
6950 PRINT "###################################"
6951 PRINT "#@@@@/////aaaaaaaallllllllllllllla#"
6952 PRINT "i...                              /"
6953 PRINT "l"
6954 PRINT "."
6955 PRINT " "
6956 PRINT " "
6957 PRINT "     l                             "
6958 PRINT "    i/                       i     "
6959 PRINT "    /@                       /     "
6960 PRINT "   .#@                      .#i    "
6961 PRINT " "
6962 PRINT " "
6963 PRINT "                                 . "
6964 PRINT " "
6965 PRINT " "
6966 PRINT " "
6967 PRINT " "
6968 PRINT " "
6969 PRINT " "
6970 PRINT " "
6971 PRINT " "
6972 PRINT "    ........iiiiiiiiiiiiiiiiiiiiiii"
6973 PRINT "///@@@@@###########################"
6974 PRINT "#######@@@@@@@/////////////////////"
6975 PRINT "iii........                        "
6976 PRINT " "
6977 PRINT " "
6978 PRINT " "
6979 PRINT " "
6980 PRINT " "
6981 PRINT " "
6982 PRINT "  .                                "
6983 PRINT " .l                                "
6984 PRINT " al                             i  "
6985 PRINT " "
6986 PRINT " "
6987 PRINT " "
6988 PRINT " "
6989 PRINT " "
6990 PRINT " "
6991 PRINT " "
6992 PRINT " "
6993 PRINT " "
6994 PRINT " "
6995 PRINT "                             .@iiil"
6996 PRINT ".illlaaaa////////////////@@@@@#####"
6997 PRINT "#####@@@@@@@////////////////@@#####"
6998 PRINT "ii.......                    .@l/##"
6999 PRINT "                              .  .l"
7000 PRINT " "
7001 PRINT " "
7002 PRINT " "
7003 PRINT " "
7004 PRINT " "
7005 PRINT " "
7006 PRINT " "
7007 PRINT " "
7008 PRINT " "
7009 PRINT " "
7010 PRINT " "
7011 PRINT " "
7012 PRINT " "
7013 PRINT " "
7014 PRINT " "
7015 PRINT " "
7016 PRINT " "
7017 PRINT "."
7018 PRINT "                                 a#"
7019 PRINT "    .......iiiiiiiiiiiiiaala.   /##"
7020 PRINT "la//@@@##########@@#########@///###"
7021 PRINT "allliiii................al/##/l/###"
7022 PRINT "                           .l/#####"
7023 PRINT "                              .l@##"
7024 PRINT "                                 a#"
7025 PRINT "                                 @#"
7026 PRINT "                                 @#"
7027 PRINT "l"
7028 PRINT " "
7029 PRINT " "
7030 PRINT " "
7031 PRINT " "
7032 PRINT " "
7033 PRINT "                                 /@"
7034 PRINT "                                 a#"
7035 PRINT "                                 .@"
7036 PRINT "a"
7037 PRINT "."
7038 PRINT "                            .      "
7039 PRINT " "
7040 PRINT " "
7041 PRINT "                            .l//.  "
7042 PRINT "                          .a####i  "
7043 PRINT "   ..iilllllaaaaaaaaa/aa..@######. "
7044 PRINT " i///////aaaaaaaaaaa//##@/#######i "
7045 PRINT "  .                  ..l/########@."
7046 PRINT "                         .a@#####/."
7047 PRINT "                           a######i"
7048 PRINT "                           @######i"
7049 PRINT "                           .a####@."
7050 PRINT "                            l####@."
7051 PRINT "                            a#####i"
7052 PRINT "                            i#####l"
7053 PRINT "                   aa.      i#####/"
7054 PRINT "                    i/a.    .######"
7055 PRINT "                      i//@i a#####@"
7056 PRINT "                        l#@a######a"
7057 PRINT " "
7058 PRINT "                            .     ."
7059 PRINT "                            /.    l"
7060 PRINT "                            il    a"
7061 PRINT "                             /i. .l"
7062 PRINT "                             i@####"
7063 PRINT "                               illl"
7064 PRINT " "
7065 PRINT "                         .li       "
7066 PRINT "                       l@##/       "
7067 PRINT "   .ilaaaa//////////@la#####i      "
7068 PRINT "   lllliiiiiiiiiiiil/@######i      "
7069 PRINT "                      i/####a      "
7070 PRINT "                       i####@      "
7071 PRINT "                       l####/      "
7072 PRINT "                        a###l      "
7073 PRINT "                        /###l      "
7074 PRINT "                 .      a###/      "
7075 PRINT "                 aa.    /###@    il"
7076 PRINT "                  .aaai./###@iia@#@"
7077 PRINT "                     @@@####@##/li "
7078 PRINT "                      /######l.    "
7079 PRINT "                 aiia@#######a.    "
7080 PRINT "               .l@#############a   "
7081 PRINT " "
7082 PRINT " "
7083 PRINT "                            i//l   "
7084 PRINT "                           i####l  "
7085 PRINT "                           a#####/i"
7086 PRINT "                          .i#######"
7087 PRINT "                          ia@@@///a"
7088 PRINT " "
7089 PRINT "                       .i          "
7090 PRINT "@a              ... .a@#/          "
7091 PRINT "#a   .la///////////@@####i         "
7092 PRINT "#/   .i............i/####i         "
7093 PRINT "#@.                  l###a         "
7094 PRINT "##l                  a###/         "
7095 PRINT "#/                   i###.         "
7096 PRINT "#/                   i###i         "
7097 PRINT "#@             ..    i###i   .     "
7098 PRINT "@a.            .llii i###aia@@.    "
7099 PRINT "li                l@/#####@l.      "
7100 PRINT "                   .@####l         "
7101 PRINT "               .al/######@ai       "
7102 PRINT "              a/al@#######la//l.   "
7103 PRINT "                ./########@i .ii   "
7104 PRINT "                l##########@       "
7105 PRINT "                      a###l        "
7106 PRINT "                      @###@        "
7107 PRINT "                      /####.       "
7108 PRINT "                      .@###l       "
7109 PRINT "                        .i@#@l.    "
7110 PRINT "                          .ia@#a.  "
7111 PRINT "                            ila/a  "
7112 PRINT " "
7113 PRINT "                      .            "
7114 PRINT "  .@l      ........ia@#.           "
7115 PRINT "  i#a  iaaa////aaa/####/l          "
7116 PRINT "  l#a  ....        /###/l          "
7117 PRINT " .@#@i              @###.          "
7118 PRINT "  @#/.              /##a           "
7119 PRINT "  a#/               /##i           "
7120 PRINT "  /#@               @##l  .        "
7121 PRINT "  /@/.        .ll.. @##al//.       "
7122 PRINT "alali           .a//###@l.         "
7123 PRINT ".                .a####a           "
7124 PRINT "              i//@######aal.       "
7125 PRINT "             ilii@######a il.      "
7126 PRINT "               .@########a         "
7127 PRINT "               /##########l        "
7128 PRINT "              .###########/        "
7129 PRINT "                 /#####..          "
7130 PRINT "                 l###/#/           "
7131 PRINT "                  .li a#a          "
7132 PRINT "                       a#a         "
7133 PRINT "                        l@/l       "
7134 PRINT "                          l//l     "
7135 PRINT "                             la.   "
7136 PRINT "                              ..   "
7137 PRINT "                     .             "
7138 PRINT "    //      ......il/#l.           "
7139 PRINT "    @/  .laaaaaaaa@####aa          "
7140 PRINT "   .#/  ....      i@###ii          "
7141 PRINT "   a##i            l###i           "
7142 PRINT "   l#/             l##a            "
7143 PRINT "   l##.            l##l            "
7144 PRINT "   a##i       .    a##l la         "
7145 PRINT "  .l//.       .lll./##@/l.         "
7146 PRINT "illi.            l@###l            "
7147 PRINT "              i.l/####@al.         "
7148 PRINT "             iaaa######lill        "
7149 PRINT "               i########l          "
7150 PRINT "               @#########i         "
7151 PRINT "              a@@########i         "
7152 PRINT "             i@../######l          "
7153 PRINT "                .####@i            "
7154 PRINT "                 l//a/@i           "
7155 PRINT "                      a#i          "
7156 PRINT "                       l@i         "
7157 PRINT "                        i/a.       "
7158 PRINT "                          illi     "
7159 PRINT "                             .  .  "
7160 PRINT " "
7161 PRINT " "
7162 PRINT "    //    ....iiiiil/#i.           "
7163 PRINT "    @/  .//aaaalll/####/a          "
7164 PRINT "   .#/            l@###i.          "
7165 PRINT "   l##l            a###i           "
7166 PRINT "   .#@             l##l            "
7167 PRINT "   i##i            l##i            "
7168 PRINT "   l#@l       .    /##i il         "
7169 PRINT " .il/a.       illl./##//a.         "
7170 PRINT "iii.            .l@###l            "
7171 PRINT "              ..l/####@ai.         "
7172 PRINT "             i/a/######lill        "
7173 PRINT "               i########i          "
7174 PRINT "              .@#########i         "
7175 PRINT "              //@########i         "
7176 PRINT "             l@ ./######l          "
7177 PRINT "            l@###.@##@.            "
7178 PRINT "            .ia//.@###/.           "
7179 PRINT "                  l#@il/.          "
7180 PRINT "                       i/.         "
7181 PRINT "                        .ai        "
7182 PRINT "                          ii       "
7183 PRINT "       .li.                 .      "
7184 PRINT "        la/ai.                     "
7185 PRINT "    ..    ..iali.l@@l.             "
7186 PRINT "   .#a         .l####a             "
7187 PRINT "   .#a           a####i            "
7188 PRINT "   i#@.          .@###la.          "
7189 PRINT "   l#@i          .##@i             "
7190 PRINT "   i#@            @#@  .           "
7191 PRINT "   l##           i##@i/@.          "
7192 PRINT "   l@@i     .lli.l###@l.           "
7193 PRINT ".ill/l        .l/####i             "
7194 PRINT "i..            i/####@//al         "
7195 PRINT "            .a@a/#####a            "
7196 PRINT "            ll..#######/.          "
7197 PRINT "               l########/          "
7198 PRINT "              i########@i          "
7199 PRINT "              @lia//a@l            "
7200 PRINT "             l/      /l            "
7201 PRINT "                  /#@/l.           "
7202 PRINT "                  .a/##@i          "
7203 PRINT "                    @###a          "
7204 PRINT "                    a###a          "
7205 PRINT "        .            lai           "
7206 PRINT "@l      .l.   .llai                "
7207 PRINT "##@.      il..@###a     ..      .  "
7208 PRINT "###/       .la####i                "
7209 PRINT "iiali        ./##a                 "
7210 PRINT "   .#a        a##/i                "
7211 PRINT "   .#a       i####@                "
7212 PRINT "   i#@.      l###l ll.             "
7213 PRINT "   l#@i      l/##/./a.             "
7214 PRINT "   .#@   .i. .i##@/i               "
7215 PRINT "   .##.   .il/@###aliii.           "
7216 PRINT "   i#@i      l####@iiii.           "
7217 PRINT ".lllal     l/######a               "
7218 PRINT "..       .aaa#######/              "
7219 PRINT "            /########i             "
7220 PRINT "            a######/i              "
7221 PRINT "             l@lii#.               "
7222 PRINT "             aa   @i               "
7223 PRINT "             /i   al               "
7224 PRINT "             @i   al               "
7225 PRINT "    ..            a#@i  l@#####.   "
7226 PRINT "     l.            i@//@######@    "
7227 PRINT "      li            i@##@//##@i    "
7228 PRINT "       il.                  .      "
7229 PRINT "        .l.  ...                   "
7230 PRINT "          ll@###/                  "
7231 PRINT "           l####a     .            "
7232 PRINT "            /##/             .     "
7233 PRINT "    i.      a##@.                  "
7234 PRINT "    @/      @##aa.             i   "
7235 PRINT "    @@     .@##l i                 "
7236 PRINT "   .@#i    /l##/  .l               "
7237 PRINT "   i@#l.lil/.##/l/ai               "
7238 PRINT "    /#i  il//###a                  "
7239 PRINT "   .##l ..ia@####allli             "
7240 PRINT "   i@@lia/ai/####l                 "
7241 PRINT ".lllal. .   @#####i                "
7242 PRINT "..          #######.               "
7243 PRINT "            @#####/                "
7244 PRINT "            i#//@a                 "
7245 PRINT "            .#. l@              .. "
7246 PRINT "            .#  .@              .. "
7247 PRINT "             @   @i                "
7248 PRINT "            .#   ai                "
7249 PRINT "     i.            a. l            "
7250 PRINT "     .l.           ./lla/@@/ai     "
7251 PRINT "       ii           ./@@//@###@.   "
7252 PRINT "        ii                 @###a.. "
7253 PRINT "         .i  l/a/l         /###i   "
7254 PRINT "          .l/####a         .a/l    "
7255 PRINT "           ./###@i i               "
7256 PRINT "            ./##.                  "
7257 PRINT "    ..      l###a        ..        "
7258 PRINT "    /@      a###i          i.      "
7259 PRINT "    /#.    .@##@                   "
7260 PRINT "    @#l i. la##@  .i               "
7261 PRINT "   .@#/  ia@l##@//al              ."
7262 PRINT "    /#l.al@@####a                  "
7263 PRINT "    @#lili..@####aali              "
7264 PRINT "   i@/l    l#####l .i              "
7265 PRINT ".illal.   .@#####/                 "
7266 PRINT "..        l######/                 "
7267 PRINT "          i@#####i                 "
7268 PRINT "            l#ii@i                 "
7269 PRINT "            i@  a/                 "
7270 PRINT "            i@  i/                 "
7271 PRINT "            ./  .@.           .i   "
7272 PRINT "            .@   @.                "
7273 PRINT "                   i      i##i     "
7274 PRINT "                   .a..laa@##@     "
7275 PRINT "                    .a/aaa####.    "
7276 PRINT "                          a##a     "
7277 PRINT "                            . i    "
7278 PRINT "               .la/@.              "
7279 PRINT "               /####.              "
7280 PRINT "               @###l               "
7281 PRINT "    .i         .@#/                "
7282 PRINT "    l#.        a##@l  ..           "
7283 PRINT "    a#.       a#####i   i          "
7284 PRINT "   .@#a      .@/##ai@i             "
7285 PRINT "   .@#/   .li/l/##l ./l            "
7286 PRINT "   ./#l   . l@a/##llaa//.          "
7287 PRINT "    /#l  laa@/@###/ii. ia.         "
7288 PRINT "   .@@l    al @###@l    .ai        "
7289 PRINT ".illal.      a######ali  .ll.      "
7290 PRINT "...        .a#######l .   .lai     "
7291 PRINT "           a########l      .ial.   "
7292 PRINT "            l@#####a        .ila.  "
7293 PRINT "             /aila@           .iai "
7294 PRINT "             /l  .#             .li"
7295 PRINT "             @.   @.               "
7296 PRINT "             #.   /i               "
7297 PRINT " "
7298 PRINT "                       .ilal.      "
7299 PRINT "                  i  illa####l     "
7300 PRINT "                        i###@.     "
7301 PRINT "                 .i.     /##l      "
7302 PRINT "              ./@##i      ..       "
7303 PRINT "             .@####.               "
7304 PRINT "              a###i                "
7305 PRINT "     .        ./#a.                "
7306 PRINT "    i#i       /###@.               "
7307 PRINT "    l#i      i###@#@i              "
7308 PRINT "   .@#l      l/##/ll/..            "
7309 PRINT "   i@#/.  ii./l##a.i/a.            "
7310 PRINT "    /#l     /@/###al.i/.           "
7311 PRINT "    a#l il//@a####l   .i.          "
7312 PRINT "    @@l .i...i#####/al. ii         "
7313 PRINT " illaa.      a######//.  .i        "
7314 PRINT " ..          /#######/    .i.      "
7315 PRINT "             @######/.      ii     "
7316 PRINT "             a##@@@.         ii    "
7317 PRINT "             /l  i@           .l.  "
7318 PRINT "             @i   #.           .l. "
7319 PRINT "             @.   /.             . "
7320 PRINT "             #.   /i               "
7321 PRINT "                      a###/   .    "
7322 PRINT "                      .@##@l.      "
7323 PRINT "                        .a##@.     "
7324 PRINT "                .         ili.     "
7325 PRINT "               ..ai                "
7326 PRINT "              /###a      .        ."
7327 PRINT "           . l###@i .              "
7328 PRINT "             i###l .ll             "
7329 PRINT "    ..        a#@l.  i             "
7330 PRINT "    a#.      a####@l.i             "
7331 PRINT "    /#.     .#@##aila/.            "
7332 PRINT "   .#@i     .@l##a   /.            "
7333 PRINT "   i##a   ilil###aiaaa.            "
7334 PRINT "   .##.   . l@###@li.ll            "
7335 PRINT "   .##i iaaaaa####l. lai           "
7336 PRINT "   i#@l      i####@la//l.          "
7337 PRINT ".illal.      a#####i i/ll.       . "
7338 PRINT ".i.          @#####l i/lli.        "
7339 PRINT "            i######i ./alli        "
7340 PRINT "             /@@/@a  ./alll.       "
7341 PRINT "             /l  l@  ./allli.      "
7342 PRINT "             @i  .#  ./alllli.     "
7343 PRINT "             @.   @. ./allllii.    "
7344 PRINT "             #.   /i  alllli.      "
7345 PRINT ".       ..         a#####/....ii.  "
7346 PRINT "                   /###@@#l.iiiii. "
7347 PRINT "                   i###l.a#@/iiiii."
7348 PRINT "             .   .. .li...illliliii"
7349 PRINT "              .ii@a.  ....iiiiilill"
7350 PRINT "             .####ali....iiiillllll"
7351 PRINT "             a###/.  laalllllllllll"
7352 PRINT "         .   i/#/aa//aiiaaaalllllla"
7353 PRINT "     .       i@###@i     .ia/aallla"
7354 PRINT "    /@      .####i          .l//aal"
7355 PRINT "    @@      l@a##i            .ia/a"
7356 PRINT "   .#@   .l.i/a##l               .i"
7357 PRINT "   l##l    ia@/##/l                "
7358 PRINT "   i#@      .@###/                 "
7359 PRINT "   .##i . ia/@####ai               "
7360 PRINT "   l##al/al. /####@lal             "
7361 PRINT " ill/a...   .######a               "
7362 PRINT "ii..        i#######i              "
7363 PRINT "            i######a               "
7364 PRINT "             //ll@a                "
7365 PRINT "             @i  l@                "
7366 PRINT "             @.  .#                "
7367 PRINT "             @    @.               "
7368 PRINT "            .#.   /i               "
7369 PRINT "                     .@##@.        "
7370 PRINT "                       .i//        "
7371 PRINT "                          a/a.     "
7372 PRINT "                  i        il      "
7373 PRINT "           .   il./.      ii       "
7374 PRINT "              i###a.   .iii        "
7375 PRINT "              /###l.i///@/         "
7376 PRINT "              i@#@@#ailai          "
7377 PRINT "             ./###/i.al.           "
7378 PRINT "    @a       /###/ iai            ."
7379 PRINT "   .#a    . .@l##@la.              "
7380 PRINT "   i#/    ill/l##@l.               "
7381 PRINT "   a#@i     a@a##a                 "
7382 PRINT "   i#/      i####/                 "
7383 PRINT "   l##.   .a//####i                "
7384 PRINT "   a#@i .aa..#####@ai              "
7385 PRINT " .il//aaa.  a######iil.            "
7386 PRINT "ili.ial.    @######/               "
7387 PRINT "           .@######/               "
7388 PRINT "            .@@//#/.               "
7389 PRINT "             @i  a/                "
7390 PRINT "            .#i  i#.               "
7391 PRINT "             #.   @.               "
7392 PRINT "             @    /i               "
7393 PRINT "                        .@####.    "
