5756 PRINT "             .########/            "
5757 PRINT "             l########/            "
5758 PRINT "             @#######@l            "
5759 PRINT "            i########l             "
5760 PRINT "            l########l             "
5761 PRINT " "
5762 PRINT " "
5763 PRINT "             ..                    "
5764 PRINT "            /@#@//l.               "
5765 PRINT "            /######@i              "
5766 PRINT "            /########.             "
5767 PRINT "           .@########a             "
5768 PRINT "           i#########/             "
5769 PRINT "            @########/             "
5770 PRINT "            .l#######@.            "
5771 PRINT "              /#####@a             "
5772 PRINT "              l/@##@ai             "
5773 PRINT "             /########/l           "
5774 PRINT "            i###########a          "
5775 PRINT "            l############.         "
5776 PRINT "            i###########l          "
5777 PRINT "             a#########/           "
5778 PRINT "              a########l           "
5779 PRINT "              i########/           "
5780 PRINT "            iaa#########.          "
5781 PRINT "            .###########l          "
5782 PRINT "             i@##########i         "
5783 PRINT "             .@#########l          "
5784 PRINT "             /#########/           "
5785 PRINT " "
5786 PRINT "                         .         "
5787 PRINT "                         l         "
5788 PRINT "            .l/@/ali     a.        "
5789 PRINT "            .@######@i   a.        "
5790 PRINT "             @########i  li        "
5791 PRINT "             @########/  /@.       "
5792 PRINT "            i#########@  a#i       "
5793 PRINT "            .##########  a#a       "
5794 PRINT "             l/@#######l /##.      "
5795 PRINT "               /######@i a##.      "
5796 PRINT "               l@@###/i  a##a      "
5797 PRINT "               l@@####@il##/       "
5798 PRINT "               @#######@/##/       "
5799 PRINT "              .###########a.       "
5800 PRINT "               a#########@         "
5801 PRINT "               l#########i         "
5802 PRINT "                @########i         "
5803 PRINT "                l########@a        "
5804 PRINT "                .##########l       "
5805 PRINT "            l@@//#########@.       "
5806 PRINT "            .@############/        "
5807 PRINT "             l##########@.         "
5808 PRINT "              ##########.          "
5809 PRINT "                            i      "
5810 PRINT "                            a      "
5811 PRINT "                   .        a.     "
5812 PRINT "                l/@#@/a.    ai     "
5813 PRINT "                l#######/.  ll     "
5814 PRINT "                a########/  i/i    "
5815 PRINT "                a#########. a@i    "
5816 PRINT "                @#########i i#/    "
5817 PRINT "                /#########a i##i   "
5818 PRINT "                .a@#######/ i##a   "
5819 PRINT "                  l######@l .##a   "
5820 PRINT "                  i@@###@l. .##/.  "
5821 PRINT "                  .@/#####a.@##i   "
5822 PRINT "                  a########/###i   "
5823 PRINT "                  /##########@.    "
5824 PRINT "                  i##########l     "
5825 PRINT "                  .#########@      "
5826 PRINT "                   /########a      "
5827 PRINT "                   i########@a.    "
5828 PRINT "                    @#########l    "
5829 PRINT "               i@@@/@#########i    "
5830 PRINT "                /############@     "
5831 PRINT "                .@##########l      "
5832 PRINT "                 a#########l       "
5833 PRINT "                              i    "
5834 PRINT "                              a    "
5835 PRINT "                   iii        /    "
5836 PRINT "                 ./@###@a.    /    "
5837 PRINT "                 .@#######l   a.   "
5838 PRINT "                 .@########.  al.  "
5839 PRINT "                 i#########a .//   "
5840 PRINT "                 a#########/  a#i  "
5841 PRINT "                 i#########@. @#/. "
5842 PRINT "                  i/#######@. @##l "
5843 PRINT "                   .######@a  /##i "
5844 PRINT "                    /a@##@l.  a##a "
5845 PRINT "                    @#######ia##@  "
5846 PRINT "                   l########@@##/  "
5847 PRINT "                   i###########a.  "
5848 PRINT "                    ##########@    "
5849 PRINT "                    /#########i    "
5850 PRINT "                    i########/     "
5851 PRINT "                     @#######@/.   "
5852 PRINT "                 .   a#########l   "
5853 PRINT "                .##@@@#########l   "
5854 PRINT "                 l############@.   "
5855 PRINT "                  a##########a     "
5856 PRINT "                  .#########a      "
5857 PRINT "                               i   "
5858 PRINT "                               a   "
5859 PRINT "                  .l@@@/l.     a.  "
5860 PRINT "                  i#######/.   li  "
5861 PRINT "                  /########@   ia. "
5862 PRINT "                  i#########i  l@i "
5863 PRINT "                  /#########l  .#a "
5864 PRINT "                  /#########/  i##i"
5865 PRINT "                  .@########@. l###"
5866 PRINT "                    a#######l  .##@"
5867 PRINT "                    l@@###@i.  .@##"
5868 PRINT "                    i@/###@@l .@##a"
5869 PRINT "                    l########.l###l"
5870 PRINT "                    l########/##@i."
5871 PRINT "                    i###########l  "
5872 PRINT "                    .##########/   "
5873 PRINT "                     /########/.   "
5874 PRINT "                     l########     "
5875 PRINT "                     i########a.   "
5876 PRINT "                .lllii#########l   "
5877 PRINT "                .@#############l   "
5878 PRINT "                 i#############i   "
5879 PRINT "                  a#########/ .    "
5880 PRINT "                  i#########/      "
5881 PRINT " "
5882 PRINT " "
5883 PRINT " "
5884 PRINT " "
5885 PRINT " "
5886 PRINT "              .a.a##@a.            "
5887 PRINT "              l#######@i           "
5888 PRINT "              l########@           "
5889 PRINT "              @#########/ai        "
5890 PRINT "              @###########l        "
5891 PRINT "              @##########@.        "
5892 PRINT "              .aa#####//l.         "
5893 PRINT "lalii           .@####li.          "
5894 PRINT "######@@/aliilai  l@#####i         "
5895 PRINT ".lial/@#########/a/######@l.       "
5896 PRINT "       ..la#################l      "
5897 PRINT "           i/###############@      "
5898 PRINT "             ...i@###########/i//  "
5899 PRINT "                 .@##############/ "
5900 PRINT "                  i#######@.a#####i"
5901 PRINT "                  .########il####ai"
5902 PRINT "                   ############@i  "
5903 PRINT "                   ###########.    "
5904 PRINT "                   #/@#######@     "
5905 PRINT " "
5906 PRINT " "
5907 PRINT " "
5908 PRINT " "
5909 PRINT " "
5910 PRINT " "
5911 PRINT "                              ..lla"
5912 PRINT "                             ia@###"
5913 PRINT "                            .l@####"
5914 PRINT "                            i/#####"
5915 PRINT "                            l/#####"
5916 PRINT "                            i/#####"
5917 PRINT "                             i/####"
5918 PRINT "                             i/####"
5919 PRINT "                             .l/a@@"
5920 PRINT "                              .lal/"
5921 PRINT "                                 .l"
5922 PRINT "                                 .l"
5923 PRINT "i"
5924 PRINT "i"
5925 PRINT "."
5926 PRINT " "
5927 PRINT " "
5928 PRINT " "
5929 PRINT " "
5930 PRINT " "
5931 PRINT " "
5932 PRINT " "
5933 PRINT " "
5934 PRINT " "
5935 PRINT " "
5936 PRINT " "
5937 PRINT " "
5938 PRINT " "
5939 PRINT " "
5940 PRINT " "
5941 PRINT "           .l                      "
5942 PRINT "     .laaaa/@a/l                   "
5943 PRINT "            i                      "
5944 PRINT " "
5945 PRINT " "
5946 PRINT " "
5947 PRINT " "
5948 PRINT " "
5949 PRINT " "
5950 PRINT " "
5951 PRINT " "
5952 PRINT " "
5953 PRINT " "
5954 PRINT " "
5955 PRINT " "
5956 PRINT " "
5957 PRINT " "
5958 PRINT " "
5959 PRINT " "
5960 PRINT " "
5961 PRINT " "
5962 PRINT " "
5963 PRINT " "
5964 PRINT " "
5965 PRINT "                  ia  .            "
5966 PRINT "           ia/////@@///            "
5967 PRINT "                  il               "
5968 PRINT " "
5969 PRINT " "
5970 PRINT " "
5971 PRINT " "
5972 PRINT " "
5973 PRINT " "
5974 PRINT " "
5975 PRINT " "
5976 PRINT " "
5977 PRINT " "
5978 PRINT " "
5979 PRINT " "
5980 PRINT " "
5981 PRINT " "
5982 PRINT " "
5983 PRINT " "
5984 PRINT " "
5985 PRINT " "
5986 PRINT " "
5987 PRINT "                        .l         "
5988 PRINT "                        i#.  ..    "
5989 PRINT "             i/@@@@#@######@@##    "
5990 PRINT "               ..iii....l#i..ii    "
5991 PRINT "                        .a         "
5992 PRINT " "
5993 PRINT " "
5994 PRINT " "
5995 PRINT " "
5996 PRINT " "
5997 PRINT " "
5998 PRINT " "
5999 PRINT " "
6000 PRINT " "
6001 PRINT " "
6002 PRINT " "
6003 PRINT " "
6004 PRINT " "
6005 PRINT " "
6006 PRINT " "
6007 PRINT " "
6008 PRINT " "
6009 PRINT " "
6010 PRINT " "
6011 PRINT "                            ......i"
6012 PRINT "                  .l//@@@@#########"
6013 PRINT "                    ila///@@@@@####"
6014 PRINT " "
6015 PRINT " "
6016 PRINT " "
6017 PRINT " "
6018 PRINT " "
6019 PRINT " "
6020 PRINT " "
6021 PRINT " "
6022 PRINT " "
6023 PRINT " "
6024 PRINT " "
6025 PRINT " "
6026 PRINT " "
6027 PRINT " "
6028 PRINT " "
6029 PRINT " "
6030 PRINT " "
6031 PRINT " "
6032 PRINT " "
6033 PRINT " "
6034 PRINT " "
6035 PRINT "                           ..ila/@#"
6036 PRINT "             ...iilllaa//@#########"
6037 PRINT "    ila//@@@####################@/l"
6038 PRINT "     .iillaaa/////###@/aaalll###ai "
6039 PRINT "                 i##@l.     l###/i."
6040 PRINT "                 /###/i    i####@ai"
6041 PRINT "                l#####a.   /#####/l"
6042 PRINT "                /#####/i  .######@a"
6043 PRINT "               .######@a. .#######/"
6044 PRINT "               .######@a.  @#####@a"
6045 PRINT "                @#####@l.  a#####@l"
6046 PRINT "                a#####/i   i#####/i"
6047 PRINT "                l#####a.   .####@ai"
6048 PRINT "                .####@a.    @###@a."
6049 PRINT " "
6050 PRINT " "
6051 PRINT " "
6052 PRINT " "
6053 PRINT " "
6054 PRINT "a"
6055 PRINT "/"
6056 PRINT "                         l/@l.     "
6057 PRINT "                       l@###@a.    "
6058 PRINT "                    .a@##/.l##/i   "
6059 PRINT "                 ia@#####l  i##@i  "
6060 PRINT "           .ila/#####/a##@i  @##@l "
6061 PRINT "..iillaa/@@####@##/l. a###a./##@#@l"
6062 PRINT "########@##al. .@#/.  @###/i####/#@"
6063 PRINT "i##a... i#@i   l###a  /###/l####al#"
6064 PRINT "l##/.   @##/.  @###/. l###l.@##@ll#"
6065 PRINT "@###l  l####l  /###/. .##@i /##@l##"
6066 PRINT "####/  l####l  a###a   @#/. l##//##"
6067 PRINT "####a  i###@i  i##@l   a#a. .##a/##"
6068 PRINT "@###l   @##/.   ##@i   i@l   @@ll##"
6069 PRINT "a##@.   a##a    /#/.   .l.   aai.##"
6070 PRINT "l##/.   l##l    l#a              /#"
6071 PRINT ".##a    .#@.    .@i              a#"
6072 PRINT " @#l     @/.     i.              i#"
6073 PRINT "                          . l######"
6074 PRINT "                        ./@a#######"
6075 PRINT "                        /##########"
6076 PRINT "                        /##########"
6077 PRINT "                        /##########"
6078 PRINT "                        i##########"
6079 PRINT "                        @##########"
6080 PRINT "                      .@##@########"
6081 PRINT "                      i/##/@#######"
6082 PRINT "           .a@/.       /##a.@######"
6083 PRINT "         i/#@a#@i      a##i l/a####"
6084 PRINT "     .ia@###. i@#l     i#@. .il@###"
6085 PRINT ".ila@###/l/#/  /##a.    al  a######"
6086 PRINT "#@/al@/. .###.i##/@/.      a#######"
6087 PRINT "@   l##i .###.a##/.@/i    i########"
6088 PRINT "#l  @##/  @#@ i##a /#@/aaa@########"
6089 PRINT "#@  /##a  a#a .##ll##l.@#a@########"
6090 PRINT "#/  l##i  i#l  /@./##/l##li########"
6091 PRINT "#l  .#@.  .@.  a/ l##la##/l########"
6092 PRINT "#.   @/    i   il i##il##aa########"
6093 PRINT "@    aa            @@..##i/########"
6094 PRINT "a    ..            //  @@.@########"
6095 PRINT ".                  ii  a/i#########"
6096 PRINT "                       lll#########"
6097 PRINT " "
6098 PRINT "                       .....       "
6099 PRINT "                   . a######a      "
6100 PRINT "                 i@@a########i     "
6101 PRINT "                 @###########a     "
6102 PRINT "                .############a     "
6103 PRINT "                 a@##########@.    "
6104 PRINT "                 i#@##########i    "
6105 PRINT "                 /#/@########@.    "
6106 PRINT "       .        i##/l@######/l     "
6107 PRINT "     i/#a       i##/ a@####a.      "
6108 PRINT "  .l@#l.@@.     .##l .ll###i       "
6109 PRINT "a@#@/#i  @#l     a@. l@#####/i     "
6110 PRINT "#ai /#/ l#@/a    .. l########@.    "
6111 PRINT "#/  @#@ /##.//.    .##########a    "
6112 PRINT "##. a#a a#@ l#//aaa/###########/@@@"
6113 PRINT "#@  i#l i#a.##i.@/la###########l.l#"
6114 PRINT "#/   @.  #i.##ll#@.i###########/ /#"
6115 PRINT "#l   l   /. @#.l##.i###########/ a#"
6116 PRINT "/.       .  /@ i#/ i###########l i#"
6117 PRINT "i           la  #l l###########i  #"
6118 PRINT "            .i  /i /##########@   /"
6119 PRINT "                i  @##########@.  ."
6120 PRINT "                   @###########.   "
6121 PRINT " "
6122 PRINT " "
6123 PRINT "                    l/////i        "
6124 PRINT "                ./ia#######i       "
6125 PRINT "               .@#@########/       "
6126 PRINT "               l###########@       "
6127 PRINT "               l@##########@       "
6128 PRINT "                l#@#########l      "
6129 PRINT "                @#l#########i      "
6130 PRINT "               i##a/######@a.      "
6131 PRINT "    .a@.       l##l @@###@.        "
6132 PRINT " .l/@ll@l      l##. ii@##a         "
6133 PRINT "/#@/@  i#/.    ./a .a@####/i       "
6134 PRINT "ai @#l a#a/.    .  /########.      "
6135 PRINT "a  ##a @#a.@l     l#########/      "
6136 PRINT "@  /#l /#l /@/aa/a@##########/@@@/a"
6137 PRINT "/  l#. l#.l#@ l#li/##########l.i#l."
6138 PRINT "l  i/  i@ l#@ @#l /##########/ a##."
6139 PRINT "i   l   a i#/ @#l a##########/ l#@ "
6140 PRINT "           @l a#. a##########l .#a "
6141 PRINT "           /. i@  /##########.  @i "
6142 PRINT "           .   a  ###########   l  "
6143 PRINT "               . .###########.     "
6144 PRINT "                 .###########.     "
6145 PRINT " "
6146 PRINT " "
6147 PRINT "                    la///a.        "
6148 PRINT "                .ai/######@.       "
6149 PRINT "               .@#@########l       "
6150 PRINT "               a###########a       "
6151 PRINT "               a###########/       "
6152 PRINT "                l###########i      "
6153 PRINT "               .@#a#########i      "
6154 PRINT "               l##a/######@l       "
6155 PRINT "    .//.       a##i #@###@.        "
6156 PRINT " .l/@ll@l      l#@. li@##a         "
6157 PRINT "/#@/@  i#/.    ./a .a@####/.       "
6158 PRINT "ai @#l a#a/.    . .@########.      "
6159 PRINT "a  ##a ##a.@l     a#########a     ."
6160 PRINT "@  /#i /#l @@a////###########@@#@aa"
6161 PRINT "/  a#  a#.l#@ l@ii/##########i l#ii"
6162 PRINT "l  i/  i/ l#@ @#l /##########a /#/."
6163 PRINT ".   i   l i#a @#i /##########l a#a "
6164 PRINT "           #i a#. /##########i i#i "
6165 PRINT "           /. i/  @#########@   @. "
6166 PRINT "           .  .l .##########@   l  "
6167 PRINT "                 .###########      "
6168 PRINT "                 .###########      "
6169 PRINT " "
6170 PRINT " "
6171 PRINT "                    laaaal         "
6172 PRINT "                .a./######a        "
6173 PRINT "               i##@########.       "
6174 PRINT "               @###########i       "
6175 PRINT "              ./###########l       "
6176 PRINT "                a##########@       "
6177 PRINT "               .##a########/       "
6178 PRINT "               a##l@######ai       "
6179 PRINT "    i/@i       a##.i@@###a.        "
6180 PRINT " .l/@ll@a      a#/  li###i         "
6181 PRINT "@#@/@. i#/.    .@l i/#####/.       "
6182 PRINT "a. @#a /#l/i    . i########@       "
6183 PRINT "/  @#a ##a.@l.    /#########l.....l"
6184 PRINT "#. /#i /#i.@/a/@@@##########@/@@@la"
6185 PRINT "/  l#  a# a#@ a@..@#########@  /#.a"
6186 PRINT "a  ./  i/ l#/ ##i @##########i.##ll"
6187 PRINT "i   .   i i#l @#. /##########. /#.i"
6188 PRINT "           @i a@  @#########@  a@  "
6189 PRINT "           a  ia  ##########a  ia  "
6190 PRINT "              .i i##########a   i  "
6191 PRINT "                 i##########/      "
6192 PRINT "                 i##########/      "
6193 PRINT " "
6194 PRINT "                     .             "
6195 PRINT "                 l/@@##/l.         "
6196 PRINT "                /########@.        "
6197 PRINT "               .##########l        "
6198 PRINT "                i#########a        "
6199 PRINT "               ./##########/i      "
6200 PRINT "             ./############/.      "
6201 PRINT "             .a/##########/.       "
6202 PRINT "      .l       /##@######/l        "
6203 PRINT "    ia@//.     @#a./@###/.         "
6204 PRINT ".la@@#. a@i    a@. ../##@.         "
6205 PRINT "@#aia#l i#@l    .  i@#####/.       "
6206 PRINT "/#. @#a @#l/l     .########a       "
6207 PRINT "##l @#i.##i @/i   /#########llaaaa/"
6208 PRINT "##. /@  @@ l#al/@@###########ll/@ a"
6209 PRINT "#a  al  /l @#a.@/ /##########i @#i/"
6210 PRINT "#.  i   a  /#il#@ a##########l @#il"
6211 PRINT "a          a@ i#a /##########. /@ i"
6212 PRINT "           ll .#i @#########/  aa ."
6213 PRINT "           i.  / .##########i  i.  "
6214 PRINT "               . l##########i      "
6215 PRINT "                 a##########i      "
6216 PRINT "                 /##########i      "
6217 PRINT " "
6218 PRINT "                    illl.          "
6219 PRINT "                  ./#####/.        "
6220 PRINT "                  @#######@        "
6221 PRINT "                .a#########l       "
6222 PRINT "                l##########i       "
6223 PRINT "                l##########l       "
6224 PRINT "               l############l      "
6225 PRINT "                .i@@#######a.      "
6226 PRINT "      .l@l         a######/.       "
6227 PRINT "   .l/#/i@a        a####al.        "
6228 PRINT "//@#/a@a .@/       l@/##@i         "
6229 PRINT ". // i## l#a/      i@#####/        "
6230 PRINT ".i##.l#@ @#ll/    .########i     .l"
6231 PRINT ".l#/ i#l @#..@@li./########@//@@/a/"
6232 PRINT " i#i .@  // /#ii@@@########@#. /@ /"
6233 PRINT " i@  .l  ai @#ll#a/##########l ##ia"
6234 PRINT " .i      i  /@ a#//##########l @# l"
6235 PRINT "            aa l#i@########@#. a/ ."
6236 PRINT "            li l@.#########//  ll  "
6237 PRINT "            .  iai#########/i  .   "
6238 PRINT "                .a#########/       "
6239 PRINT "                 @#########/       "
6240 PRINT "                .##########a       "
6241 PRINT " "
6242 PRINT "                    iaali          "
6243 PRINT "                  i@#####/         "
6244 PRINT "                 .########/        "
6245 PRINT "                .##########.       "
6246 PRINT "                .##########.       "
6247 PRINT "               ./#########@.       "
6248 PRINT "               a/@#########/.      "
6249 PRINT "                 ia########i.      "
6250 PRINT "      .a/i         @######l        "
6251 PRINT "   .l/#ll@i        i/@###i         "
6252 PRINT "//@#/a#i i#l        i/###l         "
6253 PRINT "ii#i i##.l#@a      /######l       ."
6254 PRINT " a#@ .##./#/aa    a#######@   ..il@"
6255 PRINT " i#@  /@ l#a.#/l.i#########@///#li#"
6256 PRINT "  /@  i@ .#la#ai@@#########@/ i#ai#"
6257 PRINT "  ./   l  /i/#/i#/@##########il#@ @"
6258 PRINT "   i      ..i#ll#@@########/#. @a a"
6259 PRINT "             @i.#@#########l@  al ."
6260 PRINT "             a. //#########ia  ii  "
6261 PRINT "             .  l/#########i.      "
6262 PRINT "                ./#########l       "
6263 PRINT "                 @#########i       "
6264 PRINT "                .##########i       "
6265 PRINT " "
6266 PRINT "                   .laai.          "
6267 PRINT "                  a######l         "
6268 PRINT "                 a########i        "
6269 PRINT "                i#########/        "
6270 PRINT "                i#########/        "
6271 PRINT "               i@#########a        "
6272 PRINT "              ./a##########l       "
6273 PRINT "                 l/#######/.       "
6274 PRINT "      iaa         i######/.        "
6275 PRINT "   .l/@l//.        l@##/l.         "
6276 PRINT "a/@#///. /@i       .a###ai         "
6277 PRINT "l@/. a#/ a#@i     i@######.       i"
6278 PRINT ".##l a#@ @#a/i    @#######a  .iii/@"
6279 PRINT " @#a .@@ a#ai#ai.l########@@///@ia#"
6280 PRINT " i#/  i@ .#aa#al#@########@#a /#ia#"
6281 PRINT "  l/   a  al/#/i#/##########@ /#li#"
6282 PRINT "   i      .il#al##########/@/ i#i @"
6283 PRINT "             @a.##########@aa  /. i"
6284 PRINT "             ll a#########@.l  i   "
6285 PRINT "              . i##########.       "
6286 PRINT "                 /#########.       "
6287 PRINT "                 @#########.       "
6288 PRINT "                 @#########        "
6289 PRINT " "
6290 PRINT "                  .ii.             "
6291 PRINT "                i/####@i           "
6292 PRINT "               i########.          "
6293 PRINT "               a########l          "
6294 PRINT "               /########a          "
6295 PRINT "              a#########/          "
6296 PRINT "             la@########@l         "
6297 PRINT "               .a@#####@l          "
6298 PRINT "     .aa         /###@@l           "
6299 PRINT "    l@ia@.       .l###i            "
6300 PRINT " ia@/#i /@i      i@####/         .a"
6301 PRINT "@a#ia#/i#@al    .#######l       l/@"
6302 PRINT "la#ai#/i#@ @/i..a#######@la/aaa@/.#"
6303 PRINT "aa#l @l @@.#/l@@@#########li@a.@@.@"
6304 PRINT ".l#. ai l/l#@.#/l#########li#@.##./"
6305 PRINT " i/  i. .l.#@i##.#########l #/ /@ l"
6306 PRINT " .i        // @@.######/##. /a al  "
6307 PRINT "           ia a/ ######a#@  li ..  "
6308 PRINT "            . .a.######a##         "
6309 PRINT "               ./######@@#         "
6310 PRINT "               i#########@         "
6311 PRINT "               /#########@         "
6312 PRINT "              .##########@         "
6313 PRINT " "
6314 PRINT "               ..                  "
6315 PRINT "            .a@###//i              "
6316 PRINT "            /#######@.             "
6317 PRINT "            @########a             "
6318 PRINT "            @#######@l             "
6319 PRINT "           a########/              "
6320 PRINT "          ia/#######i              "
6321 PRINT "             l#####/               "
6322 PRINT "           ...l/###.    iai        "
6323 PRINT "          l@@l l##@    a#@@l       "
6324 PRINT "         l@//#@@###.ii/aa@##a.     "
6325 PRINT "       ./#####a####@@#@#a .l#@a.   "
6326 PRINT "      ./###@/l/######@@iai  .a##/i "
6327 PRINT "     l@#ali  /#######ili      ia@#/"
6328 PRINT "   .a##@.   a@@#####@i          .la"
6329 PRINT " .l@@@/i   .i /###/#@.             "
6330 PRINT "l@##l         a#####@              "
6331 PRINT "#@@/          a#####/              "
6332 PRINT "/           .a######a              "
6333 PRINT ".          .@#@#####a              "
6334 PRINT "          .@@.@#####@              "
6335 PRINT "          l#l #######i             "
6336 PRINT "          l#a.#######/             "
6337 PRINT " "
6338 PRINT "                ...                "
6339 PRINT "             a@####a.l.            "
6340 PRINT "            i#########@.           "
6341 PRINT "            i##########l           "
6342 PRINT "            l#########@l           "
6343 PRINT "           l#########a             "
6344 PRINT "           .i@#######/             "
6345 PRINT "             l@######/             "
6346 PRINT "        /l   i.l##/##l             "
6347 PRINT "       a##l   a@####/        l/i   "
6348 PRINT "      i#@i@@al######@     .l@#//ai."
6349 PRINT "      ili il@########///l/@ila./##l"
6350 PRINT "             a#######i@#i/@.   .i@l"
6351 PRINT "             .@######.l.         l#"
6352 PRINT "              @######.           .a"
6353 PRINT "              /######i             "
6354 PRINT "              a######i             "
6355 PRINT "              /######.             "
6356 PRINT "             .######@              "
6357 PRINT "             a#######.             "
6358 PRINT "             @#######l             "
6359 PRINT "            i########@.            "
6360 PRINT "            l#########l            "
6361 PRINT " "
6362 PRINT " "
6363 PRINT "               iiili               "
6364 PRINT "              a#####@.i            "
6365 PRINT "             .#######@#/           "
6366 PRINT "             .##########i          "
6367 PRINT "             i#########@.          "
6368 PRINT "            ./@######/#@           "
6369 PRINT "              a#####@a##i          "
6370 PRINT "              i//##/..##l          "
6371 PRINT "   ./l         i/#@i  a#i     .    "
6372 PRINT " .l@/#@l.     a#####/..i    i//a   "
6373 PRINT "/##@@/ia@/aa/a#######aii..laa#/@/. "
6374 PRINT "#a. ./#@@@@l a#######@la####@a.aa@l"
6375 PRINT "l            l#######@  laaai   .@/"
6376 PRINT "             l#######@             "
6377 PRINT "             l#######/             "
6378 PRINT "             /#######/             "
6379 PRINT "            .########@             "
6380 PRINT "            i#@#######             "
6381 PRINT "            a#########.            "
6382 PRINT "            /@########i            "
6383 PRINT "            ##########l            "
6384 PRINT "           .##########a            "
6385 PRINT " "
6386 PRINT " "
6387 PRINT "               ...i.               "
6388 PRINT "              a#####a              "
6389 PRINT "             .#######@l            "
6390 PRINT "             i#########l           "
6391 PRINT "             i#########/           "
6392 PRINT "            ./#######a#a           "
6393 PRINT "             .@#####@l#/           "
6394 PRINT "              .@##@/..##           "
6395 PRINT "   i.          l@#/i  a@     .     "
6396 PRINT "  aaa/l.      /#####a  .   iaaa    "
6397 PRINT "./#a.@/aaiilaa#######lli.la#aa@/.  "
6398 PRINT "@i/@ @ai#a@/i########/l#/#a///i/@l."
6399 PRINT "#.i/ ill#/#ii########/./#@. . /@a@@"
6400 PRINT "#. .   i@@i a#########  i.     .a/@"
6401 PRINT "a       i.  i@#######/.            "
6402 PRINT "            i#/######/             "
6403 PRINT "            @@a#####@#.            "
6404 PRINT "           i#i/#####/#l            "
6405 PRINT "           @ai#######//            "
6406 PRINT "         .@#.a#######/@            "
6407 PRINT "         /#l @#######@#i           "
6408 PRINT "         @#li##########l           "
6409 PRINT " "
6410 PRINT " "
6411 PRINT "               iiii.               "
6412 PRINT "             .@#####l              "
6413 PRINT "             a########a            "
6414 PRINT "             a#########i           "
6415 PRINT "             /#########l           "
6416 PRINT "            i@######//#.           "
6417 PRINT "             i@#####a@#i           "
6418 PRINT "              i@##// /#i           "
6419 PRINT "   ..          l##ai a@      li    "
6420 PRINT "  i/aai       /#####l.i   .a/i/a   "
6421 PRINT " l@a.a#aliill/#######aalla/#aa@l/i "
6422 PRINT "@a.#/i#a//l@a########a@a/#@/l#l.///"
6423 PRINT "//.i#.i@a#l#/########@@l#/i.a..@@.a"
6424 PRINT "l#l .l ../l/#########/.a.     /l./#"
6425 PRINT " i/   ii  l.@#@######a          ll."
6426 PRINT ". ..  l/ai./#@a#####@@            ."
6427 PRINT ".      @###@l a#####/#i            "
6428 PRINT "        .ii   @#####/#a            "
6429 PRINT "             i#######/@            "
6430 PRINT "             a#######a#.           "
6431 PRINT "             @#######/#l           "
6432 PRINT "            i#########@a           "
6433 PRINT " "
6434 PRINT " "
6435 PRINT "              .lllli               "
6436 PRINT "             .######ai             "
6437 PRINT "             a########@.           "
6438 PRINT "             a#########l           "
6439 PRINT "             /#########i           "
6440 PRINT "            i/######@/#.           "
6441 PRINT "             i@#####a@#i           "
6442 PRINT "              ia##/a /#l           "
6443 PRINT "   ..         .l@#/i l@.    .a/.   "
6444 PRINT "  ./a/l.      /#####a.i   ia@ii@i  "
6445 PRINT " l//.l@aaiila/#######//al/la#.@/a/i"
6446 PRINT "//.#/i#ia@.@/########a@ai#i// #a.@a"
6447 PRINT "a@.l/ all#.a##########/.a/ a. @.l#i"
6448 PRINT "i#l l  . al a########/  /. .  i i@ "
6449 PRINT " ia       . i#/######/  .       .a "
6450 PRINT ".          a#/l#####@#.            "
6451 PRINT "       .ii@#a l#####/#l            "
6452 PRINT "     ../##a.  /#####@@/            "
6453 PRINT "     l//l.   i#######/@            "
6454 PRINT "             a#######/#.           "
6455 PRINT "             @#######@@l           "
6456 PRINT "            i##########a           "
6457 PRINT " "
6458 PRINT " "
6459 PRINT "              .lllli               "
6460 PRINT "             .@#####/i.            "
6461 PRINT "             l########@.           "
6462 PRINT "             l#########a           "
6463 PRINT "             a#########a           "
6464 PRINT "            .a#######a#i           "
6465 PRINT "             ./#####//#a           "
6466 PRINT "              ./@#/a a#a           "
6467 PRINT "   .l.         l@#@l i#i     ia.   "
6468 PRINT "  i/l/ai      a#####/ i    l/ai/.  "
6469 PRINT ".a@@.//ialllaa#######/aalaa.@/.#@a."
6470 PRINT "@al#./a @a.@a@#######aa@ a@ a@.@//#"
6471 PRINT "@/ia l. @a /@@#######a@/ a@  / ./a#"
6472 PRINT "/l      l. ./########/@. ./  .  i.a"
6473 PRINT ".           l#/######@i   i        "
6474 PRINT "           a#/l#####@#.            "
6475 PRINT "       .i.@#a l#####/#l            "
6476 PRINT "      ./##/.  /#####@@/            "
6477 PRINT "     l//l.   i#######@@            "
6478 PRINT "             a#######/#.           "
6479 PRINT "             @#######@#i           "
6480 PRINT "            .##########l           "
6481 PRINT " "
6482 PRINT " "
6483 PRINT "               lllal.              "
6484 PRINT "              @#####@i.            "
6485 PRINT "             i########@i           "
6486 PRINT "             i#########/           "
6487 PRINT "             a#########/           "
6488 PRINT "            .a#######a#a           "
6489 PRINT "             ./#####/a#/           "
6490 PRINT "               /@#@/.i#@           "
6491 PRINT "   ia.         i/#@l  @a      i    "
6492 PRINT "  l/i//i      l#####/.i    .a/a/.  "
6493 PRINT "i/#@.@aiaalaaa#######/lliiala/.@@i "
6494 PRINT "@l@/i#i.@i.@i@#######/i@ll@.i#l@#//"
6495 PRINT "#l@.ia l#.i#i/#######/.#a.#a aai@/#"
6496 PRINT "@.i .  la .@ @#######/ /a a/  l ia@"
6497 PRINT ".      .   ii#@######@ ia  a      ."
6498 PRINT "           a#@l#####@#. .          "
6499 PRINT "       .../#a.l#####a#a            "
6500 PRINT "      ./##/.  /#####//@            "
6501 PRINT "    .l//l.   .#######a#.           "
6502 PRINT "             a#######a@l           "
6503 PRINT "             @#######@//           "
6504 PRINT "            .#########/@           "
6505 PRINT " "
6506 PRINT " "
6507 PRINT "               lalal.              "
6508 PRINT "              /######i.            "
6509 PRINT "             .#########l           "
6510 PRINT "             .#########@           "
6511 PRINT "             l#########@.          "
6512 PRINT "            .a@######a#/           "
6513 PRINT "             ./#####@a##           "
6514 PRINT "               /@##/i.##.          "
6515 PRINT "   lai         i/#@i  //           "
6516 PRINT "  a/.//i      i#####/ .i    .a/a   "
6517 PRINT "l@@/.@ai/lllal#######aii .ia// a/. "
6518 PRINT "@i@@.#l.@ii@.@########l@aa@.l#i#@@l"
6519 PRINT "#l/l.@ l#i/@./#######@ /@.#l.#.@al@"
6520 PRINT "@.a .l l/ /l @#######@ i#./a a.iaa#"
6521 PRINT "l      l. a .#@#######. li.l    ..#"
6522 PRINT "           l@@l#####a#/. .i/      l"
6523 PRINT "         ./#/.l#####li@@/##a       "
6524 PRINT "       /#@/i  a#####a .a//a        "
6525 PRINT "    .a@@ai   .#######.             "
6526 PRINT "             a#######a             "
6527 PRINT "             @#######@             "
6528 PRINT "            .#########.            "
6529 PRINT " "
6530 PRINT " "
6531 PRINT "              .a////l              "
6532 PRINT "              @######ai            "
6533 PRINT "             i#########a           "
6534 PRINT "             .##########.          "
6535 PRINT "             a#######@#@.          "
6536 PRINT "            .a@######a#@           "
6537 PRINT "             .a#####@l##.          "
6538 PRINT "               //##/i @#i          "
6539 PRINT "   a/l         i/#@l  /@           "
6540 PRINT " i@l.//l      l#####a .i    .l//.  "
6541 PRINT "///@.@/./ala/a#######aii. ia// l@. "
6542 PRINT "@.a#.//.#il@.@########a@aa@./#.#a@a"
6543 PRINT "#ai@ lli#l/@.@########.@@l#iaai#ii@"
6544 PRINT "#i a .i @./l @#######@ l@.#.l.ia #/"
6545 PRINT "/.      a a.i#########. a a   ...#i"
6546 PRINT ".         .l#@a#####a#@i        .l "
6547 PRINT "         ./#/.a#####li@#/i.        "
6548 PRINT "      ./@@@i  /#####a  i/##l       "
6549 PRINT "    ia@#/l   .#######.   .a#/a     "
6550 PRINT "      ..     a#######a     .i.     "
6551 PRINT "             @#######@             "
6552 PRINT "            .#########.            "
6553 PRINT " "
6554 PRINT " "
6555 PRINT "              i/@@@@a              "
6556 PRINT "             .#######al            "
6557 PRINT "             l#########/           "
6558 PRINT "             i##########.          "
6559 PRINT "            ./#######@#@.          "
6560 PRINT "            .a#######a##.          "
6561 PRINT "             ./#####/l##i          "
6562 PRINT "               //#@ai @#i          "
6563 PRINT "  ./a.         i/#@i  a@.          "
6564 PRINT " i@ii@ai      a#####a .i    .l//i  "
6565 PRINT "a/// @/l/llaaa#######aii. ia/@ i@l "
6566 PRINT "@ a#./@.#ll@i#########a@aa@./#.@a//"
6567 PRINT "#l.@.i/.#aa#i@########i#al#i/ai#ii@"
6568 PRINT "@a l. l /ll@.@#######@.@la@ a la @@"
6569 PRINT "la      il.ai#########./.li . i .#i"
6570 PRINT " i       . a@@a#####a#@l .      ii "
6571 PRINT "         ./#@.a#####ai@#/.         "
6572 PRINT "      .a/@@l  /#####a  l@##a       "
6573 PRINT "    il/#@a.  .#######.   i/@ai     "
6574 PRINT "     ili     a#######a     ill     "
