23505 PRINT "            .@#@                   "
23506 PRINT "             i@#i                  "
23507 PRINT "              i@/                  "
23508 PRINT "               .ai                 "
23509 PRINT "                 .                 "
23510 PRINT "                                   "
23511 PRINT "                                   "
23512 PRINT "                                   "
23513 PRINT "                                   "
23514 PRINT "                                   "
23515 PRINT "                                   "
23516 PRINT "                                   "
23517 PRINT "                                   "
23518 PRINT "                                   "
23519 PRINT "                                   "
23520 PRINT "                                   "
23521 PRINT "          .####i                   "
23522 PRINT "           l###a                   "
23523 PRINT "            /##@                   "
23524 PRINT "            .@##.                  "
23525 PRINT "             .@#l                  "
23526 PRINT "              ./@                  "
23527 PRINT "                al                 "
23528 PRINT "                 .                 "
23529 PRINT "                                   "
23530 PRINT "                 i                 "
23531 PRINT "                                   "
23532 PRINT "                                   "
23533 PRINT "                                   "
23534 PRINT "                                   "
23535 PRINT "                                   "
23536 PRINT "                                   "
23537 PRINT "                                   "
23538 PRINT "                                   "
23539 PRINT "                                   "
23540 PRINT "                                   "
23541 PRINT "                                   "
23542 PRINT "                                   "
23543 PRINT "                                   "
23544 PRINT "                                   "
23545 PRINT "             .##l                  "
23546 PRINT "              i#/                  "
23547 PRINT "               ./i                 "
23548 PRINT "                 .                 "
23549 PRINT "                                   "
23550 PRINT "                                   "
23551 PRINT "                                   "
23552 PRINT "                                   "
23553 PRINT "                                   "
23554 PRINT "                                   "
23555 PRINT "                                   "
23556 PRINT "                                   "
23557 PRINT "                                   "
23558 PRINT "                                   "
23559 PRINT "                                   "
23560 PRINT "                                   "
23561 PRINT "                                   "
23562 PRINT "                                   "
23563 PRINT "                                   "
23564 PRINT "                 l                 "
23565 PRINT "                                   "
23566 PRINT "                                   "
23567 PRINT "                                   "
23568 PRINT "                                   "
23569 PRINT "                                   "
23570 PRINT "                                   "
23571 PRINT "                                   "
23572 PRINT "                                   "
23573 PRINT "                                   "
23574 PRINT "                                   "
23575 PRINT "                                   "
23576 PRINT "                                   "
23577 PRINT "                                   "
23578 PRINT "                                   "
23579 PRINT "                                   "
23580 PRINT "                                   "
23581 PRINT "                                   "
23582 PRINT "                                   "
23583 PRINT "                                   "
23584 PRINT "                                   "
23585 PRINT "                                   "
23586 PRINT "                                   "
23587 PRINT "                                   "
23588 PRINT "                 .                 "
23589 PRINT "                ./                 "
23590 PRINT "                                   "
23591 PRINT "                                   "
23592 PRINT "                                   "
23593 PRINT "                                   "
23594 PRINT "                                   "
23595 PRINT "                                   "
23596 PRINT "                                   "
23597 PRINT "                                   "
23598 PRINT "                                   "
23599 PRINT "                                   "
23600 PRINT "                                   "
23601 PRINT "                                   "
23602 PRINT "                                   "
23603 PRINT "                                   "
23604 PRINT "                                   "
23605 PRINT "                                   "
23606 PRINT "                 i                 "
23607 PRINT "                .a                 "
23608 PRINT "                                   "
23609 PRINT "                                   "
23610 PRINT "                                   "
23611 PRINT "                                   "
23612 PRINT "                                   "
23613 PRINT "                                   "
23614 PRINT "                                   "
23615 PRINT "                                   "
23616 PRINT "                                   "
23617 PRINT "                                   "
23618 PRINT "                                   "
23619 PRINT "                                   "
23620 PRINT "                                   "
23621 PRINT "                                   "
23622 PRINT "                                   "
23623 PRINT "                                   "
23624 PRINT "                                   "
23625 PRINT "                                   "
23626 PRINT "                ./.                "
23627 PRINT "                 i                 "
23628 PRINT "                                   "
23629 PRINT "                                   "
23630 PRINT "                                   "
23631 PRINT "                                   "
23632 PRINT "                                   "
23633 PRINT "                                   "
23634 PRINT "                                   "
23635 PRINT "                                   "
23636 PRINT "                                   "
23637 PRINT "                                   "
23638 PRINT "                                   "
23639 PRINT "                                   "
23640 PRINT "                                   "
23641 PRINT "                                   "
23642 PRINT "                                   "
23643 PRINT "                                   "
23644 PRINT "                                   "
23645 PRINT "                                   "
23646 PRINT "                                   "
23647 PRINT "                 /l                "
23648 PRINT "                 ai                "
23649 PRINT "                                   "
23650 PRINT "                                   "
23651 PRINT "                                   "
23652 PRINT "                                   "
23653 PRINT "                                   "
23654 PRINT "                                   "
23655 PRINT "                                   "
23656 PRINT "                                   "
23657 PRINT "                                   "
23658 PRINT "                                   "
23659 PRINT "                                   "
23660 PRINT "                                   "
23661 PRINT "                                   "
23662 PRINT "                                   "
23663 PRINT "                                   "
23664 PRINT "                                   "
23665 PRINT "                                   "
23666 PRINT "                                   "
23667 PRINT "                                   "
23668 PRINT "                 l.                "
23669 PRINT "                l#/                "
23670 PRINT "                .l.                "
23671 PRINT "                                   "
23672 PRINT "                                   "
23673 PRINT "                                   "
23674 PRINT "                                   "
23675 PRINT "                                   "
23676 PRINT "                                   "
23677 PRINT "                                   "
23678 PRINT "                                   "
23679 PRINT "                                   "
23680 PRINT "                                   "
23681 PRINT "                                   "
23682 PRINT "                                   "
23683 PRINT "                                   "
23684 PRINT "                                   "
23685 PRINT "                                   "
23686 PRINT "                                   "
23687 PRINT "                                   "
23688 PRINT "                                   "
23689 PRINT "                                   "
23690 PRINT "                                   "
23691 PRINT "                                   "
23692 PRINT "                                   "
23693 PRINT "                a/i                "
23694 PRINT "               i##/                "
23695 PRINT "               ./@i                "
23696 PRINT "                                   "
23697 PRINT "                                   "
23698 PRINT "                                   "
23699 PRINT "                                   "
23700 PRINT "                                   "
23701 PRINT "                                   "
23702 PRINT "                                   "
23703 PRINT "                                   "
23704 PRINT "                                   "
23705 PRINT "                                   "
23706 PRINT "                                   "
23707 PRINT "                                   "
23708 PRINT "                                   "
23709 PRINT "                                   "
23710 PRINT "                                   "
23711 PRINT "                                   "
23712 PRINT "                                   "
23713 PRINT "                                   "
23714 PRINT "                                   "
23715 PRINT "                                   "
23716 PRINT "                                   "
23717 PRINT "                                   "
23718 PRINT "                                   "
23719 PRINT "                                   "
23720 PRINT "                                   "
23721 PRINT "                                   "
23722 PRINT "                                   "
23723 PRINT "                ..                 "
23724 PRINT "               i@@l                "
23725 PRINT "               a##@                "
23726 PRINT "               i##a                "
23727 PRINT "                .i                 "
23728 PRINT "                                   "
23729 PRINT "                                   "
23730 PRINT "                                   "
23731 PRINT "                                   "
23732 PRINT "                                   "
23733 PRINT "                                   "
23734 PRINT "                                   "
23735 PRINT "                                   "
23736 PRINT "                                   "
23737 PRINT "                                   "
23738 PRINT "                                   "
23739 PRINT "                                   "
23740 PRINT "                                   "
23741 PRINT "                                   "
23742 PRINT "                                   "
23743 PRINT "                                   "
23744 PRINT "                                   "
23745 PRINT "                                   "
23746 PRINT "                                   "
23747 PRINT "                                   "
23748 PRINT "              .lalali              "
23749 PRINT "              /#####/              "
23750 PRINT "              a#####l              "
23751 PRINT "              a#####l              "
23752 PRINT "             l@#####/l             "
23753 PRINT "             l/@###@/l             "
23754 PRINT "              iilali.              "
23755 PRINT "                                   "
23756 PRINT "                                   "
23757 PRINT "                                   "
23758 PRINT "                                   "
23759 PRINT "                                   "
23760 PRINT "                                   "
23761 PRINT "                                   "
23762 PRINT "                                   "
23763 PRINT "                                   "
23764 PRINT "                                   "
23765 PRINT "                                   "
23766 PRINT "                                   "
23767 PRINT "                                   "
23768 PRINT "                                   "
23769 PRINT "                                   "
23770 PRINT "                                   "
23771 PRINT "              . i i .              "
23772 PRINT "            .l/a@/@a/l..           "
23773 PRINT "           ./#########/.           "
23774 PRINT "            /#########a            "
23775 PRINT "           .a#########l.           "
23776 PRINT "         .a############@a          "
23777 PRINT "         /#@a#########a##a         "
23778 PRINT "        .##@l#########l@##.        "
23779 PRINT "        .@##al@#####/l/##/         "
23780 PRINT "         ./##@/aaaaa/###a.         "
23781 PRINT "           .a/@#####@/l.           "
23782 PRINT "               .....               "
23783 PRINT "                                   "
23784 PRINT "                                   "
23785 PRINT "                                   "
23786 PRINT "                                   "
23787 PRINT "                                   "
23788 PRINT "                                   "
23789 PRINT "                                   "
23790 PRINT "                                   "
23791 PRINT "                                   "
23792 PRINT "                                   "
23793 PRINT "                  .  .             "
23794 PRINT "          i li /. @../ li          "
23795 PRINT "        ii@...         li/i        "
23796 PRINT "        @l               l#i       "
23797 PRINT "       .//..          .l.@@        "
23798 PRINT "         a.@l.laa.//ail#i..        "
23799 PRINT "          .l//#######//..          "
23800 PRINT "        .ii@###########@li.        "
23801 PRINT "      .li i##@allllla@##i il.      "
23802 PRINT "     il.   l/liaaaaail/l   .l.     "
23803 PRINT "    .li    .#@/@@/@@/@#.    il     "
23804 PRINT "    .li     l########@l     il.    "
23805 PRINT "    .li      .la///al.      ll.    "
23806 PRINT "     .li                   il.     "
23807 PRINT "      .ii.               .ii.      "
23808 PRINT "        .ii.           .ii.        "
23809 PRINT "                                   "
23810 PRINT "                                   "
23811 PRINT "                                   "
23812 PRINT "                                   "
23813 PRINT "                                   "
23814 PRINT "                                   "
23815 PRINT "                                   "
23816 PRINT "                                   "
23817 PRINT "                                   "
23818 PRINT "           .  .l  il  l.           "
23819 PRINT "        l. ai .i  ..  l  /i        "
23820 PRINT "     .l l.               . i@      "
23821 PRINT "     aa                     ./l    "
23822 PRINT "    i@i                     l/.    "
23823 PRINT "     i#l                 i. aa     "
23824 PRINT "      i .@l   ......i.  .#/        "
23825 PRINT "         aila/#/lll/#@al...        "
23826 PRINT "        .a#/i a.    l.i/@a.        "
23827 PRINT "       .@#l             a#@.       "
23828 PRINT "       /#@.             .@#a       "
23829 PRINT "       /##i             i##a       "
23830 PRINT "       i@#@i           l@#@.       "
23831 PRINT "        .a##@ai.....ia@#@a.        "
23832 PRINT "          l/###@@@@####/i          "
23833 PRINT "                                   "
23834 PRINT "                                   "
23835 PRINT "                                   "
23836 PRINT "                                   "
23837 PRINT "                                   "
23838 PRINT "                                   "
23839 PRINT "                                   "
23840 PRINT "                                   "
23841 PRINT "                                   "
23842 PRINT "                                   "
23843 PRINT "                                   "
23844 PRINT "                                   "
23845 PRINT "          ..  .l   a   l           "
23846 PRINT "       i  ll  .i   i   a  .a       "
23847 PRINT "       /                   i  i    "
23848 PRINT "   .@.                       i@.   "
23849 PRINT "   ..                          il  "
23850 PRINT "  l@  ...                 ...  la  "
23851 PRINT "   iii.        .iii.        ii.a.  "
23852 PRINT "   @@.       ./#####/.       .a#i  "
23853 PRINT "   ai  .     a#######l     i. il   "
23854 PRINT "  .l. i#l    .a@###/l     l#l .l.  "
23855 PRINT "  .l. .a.   ./i     l/    .l. .l.  "
23856 PRINT "  .l.       i#a     @#.       il   "
23857 PRINT "                                   "
23858 PRINT "                                   "
23859 PRINT "                                   "
23860 PRINT "                                   "
23861 PRINT "                                   "
23862 PRINT "                                   "
23863 PRINT "                                   "
23864 PRINT "                                   "
23865 PRINT "                                   "
23866 PRINT "                                   "
23867 PRINT "                                   "
23868 PRINT "                                   "
23869 PRINT "                                   "
23870 PRINT "                                   "
23871 PRINT "                                   "
23872 PRINT "                                   "
23873 PRINT "                                   "
23874 PRINT "                                   "
23875 PRINT "             ilaaaaal.             "
23876 PRINT "          .a@#//##/a/#@a.          "
23877 PRINT "         i##@i l##@  i@#@i         "
23878 PRINT "         @##l  i@#/   a##/         "
23879 PRINT "         /##@.       i@##/         "
23880 PRINT "         l###@l.   .l####i         "
23881 PRINT "                                   "
23882 PRINT "                                   "
23883 PRINT "                                   "
23884 PRINT "                                   "
23885 PRINT "                                   "
23886 PRINT "                                   "
23887 PRINT "                                   "
23888 PRINT "                                   "
23889 PRINT "                                   "
23890 PRINT "                                   "
23891 PRINT "                                   "
23892 PRINT "                                   "
23893 PRINT "                                   "
23894 PRINT "               .ll                 "
23895 PRINT "               @##/                "
23896 PRINT "              .###@                "
23897 PRINT "               /##l                "
23898 PRINT "                @#a                "
23899 PRINT "           .iiil###iii..           "
23900 PRINT "        illi.  i###.  .ill.        "
23901 PRINT "      i/a.     i###i     .aa.      "
23902 PRINT "     l@l       l###i       a@i     "
23903 PRINT "    i@a        l###i       ./@.    "
23904 PRINT "    l@l         ili         a@l    "
23905 PRINT "                                   "
23906 PRINT "                                   "
23907 PRINT "                                   "
23908 PRINT "                                   "
23909 PRINT "                                   "
23910 PRINT "                                   "
23911 PRINT "                                   "
23912 PRINT "                                   "
23913 PRINT "                                   "
23914 PRINT "                                   "
23915 PRINT "                                   "
23916 PRINT "                                   "
23917 PRINT "                                   "
23918 PRINT "               l@@l                "
23919 PRINT "              .####.               "
23920 PRINT "              .###@                "
23921 PRINT "               l##/                "
23922 PRINT "               i###.               "
23923 PRINT "               i###i               "
23924 PRINT "               l###i               "
23925 PRINT "               l###i               "
23926 PRINT "            .la@###@ai             "
23927 PRINT "           l@#########@i           "
23928 PRINT "          .@###a###a###@           "
23929 PRINT "                                   "
23930 PRINT "                                   "
23931 PRINT "                                   "
23932 PRINT "                                   "
23933 PRINT "                                   "
23934 PRINT "                                   "
23935 PRINT "                                   "
23936 PRINT "                                   "
23937 PRINT "                                   "
23938 PRINT "                                   "
23939 PRINT "                                   "
23940 PRINT "                                   "
23941 PRINT "                 .                 "
23942 PRINT "               l@#@.               "
23943 PRINT "               l###i               "
23944 PRINT "               l###i               "
23945 PRINT "               i###i               "
23946 PRINT "               l###l               "
23947 PRINT "               a###a               "
23948 PRINT "               @###@               "
23949 PRINT "          .la/a@####aaai.          "
23950 PRINT "        ia@ai  @###@  ia@a.        "
23951 PRINT "       l@/.    #####    i@@l       "
23952 PRINT "      i@@l    .#####.    a@@.      "
23953 PRINT "                                   "
23954 PRINT "                                   "
23955 PRINT "                                   "
23956 PRINT "                                   "
23957 PRINT "                                   "
23958 PRINT "                                   "
23959 PRINT "                                   "
23960 PRINT "                                   "
23961 PRINT "                                   "
23962 PRINT "                                   "
23963 PRINT "                                   "
23964 PRINT "                                   "
23965 PRINT "                iai                "
23966 PRINT "               a###a               "
23967 PRINT "               .###i               "
23968 PRINT "               .###a               "
23969 PRINT "               i###a               "
23970 PRINT "               a###/               "
23971 PRINT "               @####.              "
23972 PRINT "              .#####l              "
23973 PRINT "              i#####l              "
23974 PRINT "              .#####i              "
23975 PRINT "              a#####a              "
23976 PRINT "              @#####@              "
23977 PRINT "                                   "
23978 PRINT "                                   "
23979 PRINT "                                   "
23980 PRINT "                                   "
23981 PRINT "                                   "
23982 PRINT "                                   "
23983 PRINT "                                   "
23984 PRINT "                                   "
23985 PRINT "                                   "
23986 PRINT "                                   "
23987 PRINT "                                   "
23988 PRINT "                iai.               "
23989 PRINT "               a###a               "
23990 PRINT "               .###i               "
23991 PRINT "               .###l               "
23992 PRINT "               l###a               "
23993 PRINT "               a###/               "
23994 PRINT "               @####.              "
23995 PRINT "              i#####l              "
23996 PRINT "              i#####l              "
23997 PRINT "              .#####i              "
23998 PRINT "              a#####a              "
23999 PRINT "              @#####@              "
24000 PRINT "             .#######.             "
24001 PRINT "                                   "
24002 PRINT "                                   "
24003 PRINT "                                   "
24004 PRINT "                                   "
24005 PRINT "                                   "
24006 PRINT "                                   "
24007 PRINT "                                   "
24008 PRINT "                                   "
24009 PRINT "                                   "
24010 PRINT "                                   "
24011 PRINT "               .l/l.               "
24012 PRINT "               a###a               "
24013 PRINT "               .###i               "
24014 PRINT "               i###l               "
24015 PRINT "               l###a               "
24016 PRINT "               a###/               "
24017 PRINT "               @####.              "
24018 PRINT "              i#####l              "
24019 PRINT "              i#####l              "
24020 PRINT "              i#####i              "
24021 PRINT "              a#####a              "
24022 PRINT "              @#####@              "
24023 PRINT "             .#######.             "
24024 PRINT "             l#######l             "
24025 PRINT "                                   "
24026 PRINT "                                   "
24027 PRINT "                                   "
24028 PRINT "                                   "
24029 PRINT "                                   "
24030 PRINT "                                   "
24031 PRINT "                                   "
24032 PRINT "                                   "
24033 PRINT "                                   "
24034 PRINT "                iai.               "
24035 PRINT "               a###a               "
24036 PRINT "               .###i               "
24037 PRINT "               .###l               "
24038 PRINT "               l###a               "
24039 PRINT "               a###/               "
24040 PRINT "               @####               "
24041 PRINT "              .#####l              "
24042 PRINT "              i#####l              "
24043 PRINT "              .#####i              "
24044 PRINT "              l#####l              "
24045 PRINT "              @#####@              "
24046 PRINT "             .#######.             "
24047 PRINT "             l#######l             "
24048 PRINT "             l#######l             "
24049 PRINT "                                   "
24050 PRINT "                                   "
24051 PRINT "                                   "
24052 PRINT "                                   "
24053 PRINT "                                   "
24054 PRINT "                                   "
24055 PRINT "                                   "
24056 PRINT "                                   "
24057 PRINT "                                   "
24058 PRINT "               la@al               "
24059 PRINT "               l###l               "
24060 PRINT "               .###i               "
24061 PRINT "               i###l               "
24062 PRINT "               l###a               "
24063 PRINT "               a###/               "
24064 PRINT "               @####.              "
24065 PRINT "              i#####a              "
24066 PRINT "              i#####l              "
24067 PRINT "              i#####i              "
24068 PRINT "              a#####a              "
24069 PRINT "              @#####@              "
24070 PRINT "             .#######.             "
24071 PRINT "             l#######l             "
24072 PRINT "             i###@###i             "
24073 PRINT "                                   "
24074 PRINT "                                   "
24075 PRINT "                                   "
24076 PRINT "                                   "
24077 PRINT "                                   "
24078 PRINT "                                   "
24079 PRINT "                                   "
24080 PRINT "                                   "
24081 PRINT "                 .                 "
24082 PRINT "               /@##/               "
24083 PRINT "               i###l               "
24084 PRINT "               .###i               "
24085 PRINT "               i###l               "
24086 PRINT "               l###a               "
24087 PRINT "               /###/               "
24088 PRINT "               #####.              "
24089 PRINT "              i#####l              "
24090 PRINT "              l#####a              "
24091 PRINT "              i#####l              "
24092 PRINT "              a#####a              "
24093 PRINT "              @#####@              "
24094 PRINT "             .#######.             "
24095 PRINT "             l#######l             "
24096 PRINT "             l###@###l             "
24097 PRINT "                                   "
24098 PRINT "                                   "
24099 PRINT "                                   "
24100 PRINT "                                   "
24101 PRINT "                                   "
24102 PRINT "                                   "
24103 PRINT "                                   "
24104 PRINT "                                   "
24105 PRINT "               illll               "
24106 PRINT "              .@###@               "
24107 PRINT "               i###i               "
24108 PRINT "               .###i               "
24109 PRINT "               l###l               "
24110 PRINT "               a###a               "
24111 PRINT "               @###@               "
24112 PRINT "              .#####.              "
24113 PRINT "              l#####a              "
24114 PRINT "              /#####/              "
24115 PRINT "              a#####a              "
24116 PRINT "              a#####a              "
24117 PRINT "              @#####@              "
24118 PRINT "             i#######.             "
24119 PRINT "             a#######l             "
24120 PRINT "             a#######a             "
24121 PRINT "                                   "
24122 PRINT "                                   "
24123 PRINT "                                   "
24124 PRINT "                                   "
24125 PRINT "                                   "
24126 PRINT "                                   "
24127 PRINT "                                   "
24128 PRINT "                                   "
24129 PRINT "              i/a//@.              "
24130 PRINT "              .####@               "
24131 PRINT "               l###i               "
24132 PRINT "               i###i               "
24133 PRINT "               l###l               "
24134 PRINT "               /###/               "
24135 PRINT "               @###@               "
24136 PRINT "              l#####.              "
24137 PRINT "              /#####a              "
24138 PRINT "             .######@              "
24139 PRINT "             .@#####/              "
24140 PRINT "              a#####a              "
24141 PRINT "              ######@              "
24142 PRINT "             i#######i             "
24143 PRINT "             a#######l             "
24144 PRINT "             @#######/             "
24145 PRINT "                                   "
24146 PRINT "                                   "
24147 PRINT "                                   "
24148 PRINT "                                   "
24149 PRINT "                                   "
24150 PRINT "                                   "
24151 PRINT "                                   "
24152 PRINT "               . ..i               "
24153 PRINT "              a#####.              "
24154 PRINT "              .####/               "
24155 PRINT "               l###i               "
24156 PRINT "               a###.               "
24157 PRINT "               /###l               "
24158 PRINT "               @###/               "
24159 PRINT "              .####@               "
24160 PRINT "              a#####.              "
24161 PRINT "              @#####/              "
24162 PRINT "             l#######.             "
24163 PRINT "             /######/i             "
24164 PRINT "             ./#####a              "
24165 PRINT "             .######@              "
24166 PRINT "             l#######i             "
24167 PRINT "             /#######l             "
24168 PRINT "             @#######/             "
24169 PRINT "                                   "
24170 PRINT "                                   "
24171 PRINT "                                   "
24172 PRINT "                                   "
24173 PRINT "                                   "
24174 PRINT "                                   "
24175 PRINT "                                   "
24176 PRINT "              lalaa/i              "
24177 PRINT "              /#####.              "
24178 PRINT "              .@###a               "
24179 PRINT "               /###i               "
24180 PRINT "               @###.               "
24181 PRINT "              i####l               "
24182 PRINT "              .####/               "
24183 PRINT "              i####/               "
24184 PRINT "              /#####.              "
24185 PRINT "             i######@.             "
24186 PRINT "             @#######a             "
24187 PRINT "            a#######a/             "
24188 PRINT "            .i@#####l              "
24189 PRINT "             .######@              "
24190 PRINT "             a#######i             "
24191 PRINT "             @#######l             "
24192 PRINT "             ########a             "
24193 PRINT "                                   "
24194 PRINT "                                   "
24195 PRINT "                                   "
24196 PRINT "                                   "
24197 PRINT "                                   "
24198 PRINT "                                   "
24199 PRINT "                ....               "
24200 PRINT "             .@@####i              "
24201 PRINT "             .@####/               "
24202 PRINT "              .####l               "
24203 PRINT "              .###@.               "
24204 PRINT "              l###@                "
24205 PRINT "              /####a               "
24206 PRINT "              a####a               "
24207 PRINT "              /####/               "
24208 PRINT "             .######i              "
24209 PRINT "             /#######l             "
24210 PRINT "            l#########l            "
24211 PRINT "           l########@la            "
24212 PRINT "           l/@@#####/              "
24213 PRINT "             i######/              "
24214 PRINT "             a#######.             "
24215 PRINT "             @#######l             "
24216 PRINT "            i########a             "
24217 PRINT "                                   "
24218 PRINT "                                   "
24219 PRINT "                                   "
24220 PRINT "                                   "
24221 PRINT "                                   "
24222 PRINT "                                   "
24223 PRINT "             illla/a               "
24224 PRINT "             @#####a               "
24225 PRINT "             a#####i               "
24226 PRINT "              /###@.               "
24227 PRINT "              @###a                "
24228 PRINT "             i####a                "
24229 PRINT "             @#####a               "
24230 PRINT "             l#####/               "
24231 PRINT "             l#####@               "
24232 PRINT "             @######a              "
24233 PRINT "            a########@.            "
24234 PRINT "           a##########@            "
24235 PRINT "          a###@######i/i           "
24236 PRINT "         ./@#l@######              "
24237 PRINT "          .ill######/              "
24238 PRINT "             /######@              "
24239 PRINT "            .########i             "
24240 PRINT "            i########a             "
24241 PRINT "                                   "
24242 PRINT "                                   "
24243 PRINT "                                   "
24244 PRINT "                                   "
24245 PRINT "                                   "
24246 PRINT "                                   "
24247 PRINT "            alila/@                "
24248 PRINT "            @#####@                "
24249 PRINT "            a#####@                "
24250 PRINT "            ./####l                "
24251 PRINT "             a####.                "
24252 PRINT "             /####i                "
24253 PRINT "            i######l               "
24254 PRINT "           .#######@               "
24255 PRINT "            /#@@####i              "
24256 PRINT "           .@#//####@.             "
24257 PRINT "          ./##a@######l            "
24258 PRINT "         .@###i@######/            "
24259 PRINT "        .@###la######iai           "
24260 PRINT "        l##@i.######@              "
24261 PRINT "        //a  l######l              "
24262 PRINT "             /######/              "
24263 PRINT "            .########.             "
24264 PRINT "            l########l             "
24265 PRINT "                                   "
24266 PRINT "                                   "
24267 PRINT "                                   "
24268 PRINT "                                   "
24269 PRINT "                                   "
24270 PRINT "                 .                 "
24271 PRINT "          .//la/@#l                "
24272 PRINT "           @######a                "
24273 PRINT "           l######a                "
24274 PRINT "            a#####i                "
24275 PRINT "            l####/                 "
24276 PRINT "            l####@.                "
24277 PRINT "            a######l               "
24278 PRINT "           a#######@               "
24279 PRINT "          l#########i              "
24280 PRINT "          .@##@#####/              "
24281 PRINT "          i###.@#####/.            "
24282 PRINT "         i###a @######a            "
24283 PRINT "        .@##@ l######/a            "
24284 PRINT "       .@##/. @#####/ i            "
24285 PRINT "      .a#@i  i######l              "
24286 PRINT "      .@@.   /######/              "
24287 PRINT "      .l.   .########              "
24288 PRINT "            i########i             "
24289 PRINT "                                   "
24290 PRINT "                                   "
24291 PRINT "                                   "
24292 PRINT "                                   "
24293 PRINT "                                   "
24294 PRINT "               .ii                 "
24295 PRINT "          @@//####.                "
24296 PRINT "          a#######l                "
24297 PRINT "          .#######a                "
24298 PRINT "           i######i                "
24299 PRINT "           i#####a                 "
24300 PRINT "           ./####/.                "
24301 PRINT "            /######i               "
24302 PRINT "            @######@               "
24303 PRINT "           a########.              "
24304 PRINT "          l#########l              "
24305 PRINT "          @#########@.             "
24306 PRINT "         .###@a@#####@i            "
24307 PRINT "         /###. @######l            "
